"""
Script to generate 50 SQL queries for the INDIA_POPULATION_CENSUS database.

Queries are inspired by Spider2 dataset complexity patterns:
- Level 1 (Simple): 10 queries - Single table, basic SELECT/WHERE/GROUP BY
- Level 2 (Moderate): 15 queries - Multiple JOINs, basic aggregations
- Level 3 (Intermediate): 12 queries - CTEs, window functions, CASE WHEN
- Level 4 (Advanced): 8 queries - Multi-CTE, complex aggregations
- Level 5 (Complex): 5 queries - Statistical calculations, rankings

Usage:
    python scripts/generate_queries.py
"""

import os
from pathlib import Path

# Define all 50 queries with metadata
QUERIES = [
    # ==========================================================================
    # LEVEL 1 - SIMPLE (10 queries)
    # Single table queries with basic aggregations
    # ==========================================================================
    {
        "id": 1,
        "level": 1,
        "category": "Population Analytics",
        "sql": """SELECT STATE, COUNT(*) AS LOCATION_COUNT
FROM LOCATIONS
GROUP BY STATE
ORDER BY LOCATION_COUNT DESC;"""
    },
    {
        "id": 2,
        "level": 1,
        "category": "Population Analytics",
        "sql": """SELECT RESIDENCE_TYPE, SUM(HOUSEHOLDS) AS TOTAL_HOUSEHOLDS
FROM CENSUS_POPULATION
GROUP BY RESIDENCE_TYPE;"""
    },
    {
        "id": 3,
        "level": 1,
        "category": "Population Analytics",
        "sql": """SELECT LOCATION_LEVEL, COUNT(*) AS COUNT
FROM LOCATIONS
GROUP BY LOCATION_LEVEL
ORDER BY COUNT DESC;"""
    },
    {
        "id": 4,
        "level": 1,
        "category": "Literacy Analysis",
        "sql": """SELECT SUM(LITERATE_TOTAL) AS TOTAL_LITERATE,
       SUM(ILLITERATE_TOTAL) AS TOTAL_ILLITERATE
FROM CENSUS_LITERACY;"""
    },
    {
        "id": 5,
        "level": 1,
        "category": "Employment Statistics",
        "sql": """SELECT SUM(WORKING_TOTAL) AS TOTAL_WORKERS,
       SUM(NON_WORKERS_TOTAL) AS TOTAL_NON_WORKERS
FROM CENSUS_WORKERS_SUMMARY;"""
    },
    {
        "id": 6,
        "level": 1,
        "category": "Caste Demographics",
        "sql": """SELECT SUM(SC_POPULATION_TOTAL) AS TOTAL_SC,
       SUM(ST_POPULATION_TOTAL) AS TOTAL_ST
FROM CENSUS_CASTE;"""
    },
    {
        "id": 7,
        "level": 1,
        "category": "Population Analytics",
        "sql": """SELECT CENSUS_YEAR, COUNT(*) AS RECORD_COUNT
FROM CENSUS_POPULATION
GROUP BY CENSUS_YEAR;"""
    },
    {
        "id": 8,
        "level": 1,
        "category": "Employment Statistics",
        "sql": """SELECT SUM(CULTIVATORS_TOTAL) AS CULTIVATORS,
       SUM(AGRI_LABOURERS_TOTAL) AS AGRI_LABOURERS,
       SUM(HOUSEHOLD_INDUSTRY_TOTAL) AS HOUSEHOLD_INDUSTRY,
       SUM(OTHER_WORKERS_TOTAL) AS OTHER_WORKERS
FROM CENSUS_MAIN_WORKERS_DETAIL;"""
    },
    {
        "id": 9,
        "level": 1,
        "category": "Geographic Aggregations",
        "sql": """SELECT STATE, COUNT(DISTINCT DISTRICT) AS DISTRICT_COUNT
FROM LOCATIONS
GROUP BY STATE
ORDER BY DISTRICT_COUNT DESC
LIMIT 10;"""
    },
    {
        "id": 10,
        "level": 1,
        "category": "Population Analytics",
        "sql": """SELECT SUM(POPULATION_TOTAL) AS TOTAL_POPULATION,
       SUM(POPULATION_MALE) AS MALE_POPULATION,
       SUM(POPULATION_FEMALE) AS FEMALE_POPULATION
FROM CENSUS_POPULATION;"""
    },

    # ==========================================================================
    # LEVEL 2 - MODERATE (15 queries)
    # Multiple JOINs with grouping and basic calculations
    # ==========================================================================
    {
        "id": 11,
        "level": 2,
        "category": "Population Analytics",
        "sql": """SELECT L.STATE, SUM(P.POPULATION_TOTAL) AS TOTAL_POPULATION
FROM LOCATIONS L
JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
GROUP BY L.STATE
ORDER BY TOTAL_POPULATION DESC;"""
    },
    {
        "id": 12,
        "level": 2,
        "category": "Population Analytics",
        "sql": """SELECT L.STATE, L.DISTRICT, SUM(P.HOUSEHOLDS) AS TOTAL_HOUSEHOLDS
FROM LOCATIONS L
JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
GROUP BY L.STATE, L.DISTRICT
ORDER BY TOTAL_HOUSEHOLDS DESC
LIMIT 20;"""
    },
    {
        "id": 13,
        "level": 2,
        "category": "Literacy Analysis",
        "sql": """SELECT L.STATE,
       SUM(LIT.LITERATE_TOTAL) AS LITERATE,
       SUM(LIT.ILLITERATE_TOTAL) AS ILLITERATE,
       ROUND(SUM(LIT.LITERATE_TOTAL) * 100.0 / NULLIF(SUM(LIT.LITERATE_TOTAL + LIT.ILLITERATE_TOTAL), 0), 2) AS LITERACY_RATE
FROM LOCATIONS L
JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
JOIN CENSUS_LITERACY LIT ON P.CENSUS_ID = LIT.CENSUS_ID
GROUP BY L.STATE
ORDER BY LITERACY_RATE DESC;"""
    },
    {
        "id": 14,
        "level": 2,
        "category": "Caste Demographics",
        "sql": """SELECT L.STATE,
       SUM(C.SC_POPULATION_TOTAL) AS SC_POPULATION,
       SUM(C.ST_POPULATION_TOTAL) AS ST_POPULATION,
       SUM(P.POPULATION_TOTAL) AS TOTAL_POPULATION
FROM LOCATIONS L
JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
JOIN CENSUS_CASTE C ON P.CENSUS_ID = C.CENSUS_ID
GROUP BY L.STATE
ORDER BY ST_POPULATION DESC;"""
    },
    {
        "id": 15,
        "level": 2,
        "category": "Employment Statistics",
        "sql": """SELECT L.STATE,
       SUM(W.WORKING_TOTAL) AS WORKERS,
       SUM(W.NON_WORKERS_TOTAL) AS NON_WORKERS,
       ROUND(SUM(W.WORKING_TOTAL) * 100.0 / NULLIF(SUM(W.WORKING_TOTAL + W.NON_WORKERS_TOTAL), 0), 2) AS EMPLOYMENT_RATE
FROM LOCATIONS L
JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
JOIN CENSUS_WORKERS_SUMMARY W ON P.CENSUS_ID = W.CENSUS_ID
GROUP BY L.STATE
ORDER BY EMPLOYMENT_RATE DESC;"""
    },
    {
        "id": 16,
        "level": 2,
        "category": "Population Analytics",
        "sql": """SELECT L.STATE, P.RESIDENCE_TYPE,
       SUM(P.POPULATION_TOTAL) AS POPULATION
FROM LOCATIONS L
JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
GROUP BY L.STATE, P.RESIDENCE_TYPE
ORDER BY L.STATE, P.RESIDENCE_TYPE;"""
    },
    {
        "id": 17,
        "level": 2,
        "category": "Literacy Analysis",
        "sql": """SELECT L.STATE,
       SUM(LIT.LITERATE_MALE) AS LITERATE_MALE,
       SUM(LIT.LITERATE_FEMALE) AS LITERATE_FEMALE,
       ROUND(SUM(LIT.LITERATE_MALE) * 1.0 / NULLIF(SUM(LIT.LITERATE_FEMALE), 0), 2) AS MALE_FEMALE_RATIO
FROM LOCATIONS L
JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
JOIN CENSUS_LITERACY LIT ON P.CENSUS_ID = LIT.CENSUS_ID
GROUP BY L.STATE
ORDER BY MALE_FEMALE_RATIO DESC;"""
    },
    {
        "id": 18,
        "level": 2,
        "category": "Employment Statistics",
        "sql": """SELECT L.STATE,
       SUM(M.CULTIVATORS_TOTAL) AS CULTIVATORS,
       SUM(M.AGRI_LABOURERS_TOTAL) AS AGRI_LABOURERS
FROM LOCATIONS L
JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
JOIN CENSUS_MAIN_WORKERS_DETAIL M ON P.CENSUS_ID = M.CENSUS_ID
GROUP BY L.STATE
ORDER BY CULTIVATORS DESC;"""
    },
    {
        "id": 19,
        "level": 2,
        "category": "Population Analytics",
        "sql": """SELECT L.STATE,
       SUM(P.POPULATION_0_6_TOTAL) AS CHILDREN_0_6,
       SUM(P.POPULATION_TOTAL) AS TOTAL_POPULATION,
       ROUND(SUM(P.POPULATION_0_6_TOTAL) * 100.0 / NULLIF(SUM(P.POPULATION_TOTAL), 0), 2) AS CHILD_PERCENTAGE
FROM LOCATIONS L
JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
GROUP BY L.STATE
ORDER BY CHILD_PERCENTAGE DESC;"""
    },
    {
        "id": 20,
        "level": 2,
        "category": "Employment Statistics",
        "sql": """SELECT L.STATE,
       SUM(W.MAIN_WORKERS_TOTAL) AS MAIN_WORKERS,
       SUM(W.MARGINAL_WORKERS_TOTAL) AS MARGINAL_WORKERS
FROM LOCATIONS L
JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
JOIN CENSUS_WORKERS_SUMMARY W ON P.CENSUS_ID = W.CENSUS_ID
GROUP BY L.STATE
ORDER BY MAIN_WORKERS DESC;"""
    },
    {
        "id": 21,
        "level": 2,
        "category": "Caste Demographics",
        "sql": """SELECT L.STATE, L.DISTRICT,
       SUM(C.ST_POPULATION_TOTAL) AS ST_POPULATION,
       ROUND(SUM(C.ST_POPULATION_TOTAL) * 100.0 / NULLIF(SUM(P.POPULATION_TOTAL), 0), 2) AS ST_PERCENTAGE
FROM LOCATIONS L
JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
JOIN CENSUS_CASTE C ON P.CENSUS_ID = C.CENSUS_ID
GROUP BY L.STATE, L.DISTRICT
HAVING SUM(C.ST_POPULATION_TOTAL) > 0
ORDER BY ST_PERCENTAGE DESC
LIMIT 20;"""
    },
    {
        "id": 22,
        "level": 2,
        "category": "Geographic Aggregations",
        "sql": """SELECT L.STATE, L.DISTRICT,
       COUNT(DISTINCT L.SUB_DISTRICT) AS SUB_DISTRICT_COUNT,
       COUNT(DISTINCT L.VILLAGE_ULB) AS VILLAGE_COUNT
FROM LOCATIONS L
GROUP BY L.STATE, L.DISTRICT
ORDER BY VILLAGE_COUNT DESC
LIMIT 20;"""
    },
    {
        "id": 23,
        "level": 2,
        "category": "Population Analytics",
        "sql": """SELECT L.STATE,
       SUM(P.POPULATION_MALE) AS MALE,
       SUM(P.POPULATION_FEMALE) AS FEMALE,
       ROUND(SUM(P.POPULATION_FEMALE) * 1000.0 / NULLIF(SUM(P.POPULATION_MALE), 0), 0) AS SEX_RATIO
FROM LOCATIONS L
JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
GROUP BY L.STATE
ORDER BY SEX_RATIO DESC;"""
    },
    {
        "id": 24,
        "level": 2,
        "category": "Employment Statistics",
        "sql": """SELECT L.STATE,
       SUM(MG.CULTIVATORS_TOTAL) AS MARGINAL_CULTIVATORS,
       SUM(MG.AGRI_LABOURERS_TOTAL) AS MARGINAL_AGRI_LABOURERS,
       SUM(MG.HOUSEHOLD_INDUSTRY_TOTAL) AS MARGINAL_HOUSEHOLD_INDUSTRY,
       SUM(MG.OTHER_WORKERS_TOTAL) AS MARGINAL_OTHER_WORKERS
FROM LOCATIONS L
JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
JOIN CENSUS_MARGINAL_WORKERS_DETAIL MG ON P.CENSUS_ID = MG.CENSUS_ID
GROUP BY L.STATE
ORDER BY MARGINAL_CULTIVATORS DESC;"""
    },
    {
        "id": 25,
        "level": 2,
        "category": "Literacy Analysis",
        "sql": """SELECT L.STATE, P.RESIDENCE_TYPE,
       SUM(LIT.LITERATE_TOTAL) AS LITERATE,
       SUM(LIT.ILLITERATE_TOTAL) AS ILLITERATE
FROM LOCATIONS L
JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
JOIN CENSUS_LITERACY LIT ON P.CENSUS_ID = LIT.CENSUS_ID
GROUP BY L.STATE, P.RESIDENCE_TYPE
ORDER BY L.STATE, P.RESIDENCE_TYPE;"""
    },

    # ==========================================================================
    # LEVEL 3 - INTERMEDIATE (12 queries)
    # CTEs, window functions, CASE WHEN statements
    # ==========================================================================
    {
        "id": 26,
        "level": 3,
        "category": "Population Analytics",
        "sql": """WITH StatePopulation AS (
    SELECT L.STATE,
           SUM(P.POPULATION_TOTAL) AS TOTAL_POPULATION
    FROM LOCATIONS L
    JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
    GROUP BY L.STATE
)
SELECT STATE, TOTAL_POPULATION,
       RANK() OVER (ORDER BY TOTAL_POPULATION DESC) AS POPULATION_RANK
FROM StatePopulation;"""
    },
    {
        "id": 27,
        "level": 3,
        "category": "Literacy Analysis",
        "sql": """WITH DistrictLiteracy AS (
    SELECT L.STATE, L.DISTRICT,
           SUM(LIT.LITERATE_TOTAL) AS LITERATE,
           SUM(LIT.LITERATE_TOTAL + LIT.ILLITERATE_TOTAL) AS TOTAL
    FROM LOCATIONS L
    JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
    JOIN CENSUS_LITERACY LIT ON P.CENSUS_ID = LIT.CENSUS_ID
    GROUP BY L.STATE, L.DISTRICT
)
SELECT STATE, DISTRICT,
       ROUND(LITERATE * 100.0 / NULLIF(TOTAL, 0), 2) AS LITERACY_RATE,
       RANK() OVER (PARTITION BY STATE ORDER BY LITERATE * 100.0 / NULLIF(TOTAL, 0) DESC) AS RANK_IN_STATE
FROM DistrictLiteracy
WHERE TOTAL > 0;"""
    },
    {
        "id": 28,
        "level": 3,
        "category": "Employment Statistics",
        "sql": """WITH WorkerStats AS (
    SELECT L.STATE, L.DISTRICT,
           SUM(W.WORKING_MALE) AS MALE_WORKERS,
           SUM(W.WORKING_FEMALE) AS FEMALE_WORKERS,
           SUM(W.WORKING_TOTAL) AS TOTAL_WORKERS
    FROM LOCATIONS L
    JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
    JOIN CENSUS_WORKERS_SUMMARY W ON P.CENSUS_ID = W.CENSUS_ID
    GROUP BY L.STATE, L.DISTRICT
)
SELECT STATE, DISTRICT,
       TOTAL_WORKERS,
       ROUND(FEMALE_WORKERS * 100.0 / NULLIF(TOTAL_WORKERS, 0), 2) AS FEMALE_WORKER_PCT,
       CASE
           WHEN FEMALE_WORKERS * 100.0 / NULLIF(TOTAL_WORKERS, 0) >= 40 THEN 'High'
           WHEN FEMALE_WORKERS * 100.0 / NULLIF(TOTAL_WORKERS, 0) >= 25 THEN 'Medium'
           ELSE 'Low'
       END AS FEMALE_PARTICIPATION_LEVEL
FROM WorkerStats
WHERE TOTAL_WORKERS > 1000
ORDER BY FEMALE_WORKER_PCT DESC;"""
    },
    {
        "id": 29,
        "level": 3,
        "category": "Caste Demographics",
        "sql": """WITH CasteDistribution AS (
    SELECT L.STATE,
           SUM(C.SC_POPULATION_TOTAL) AS SC_POP,
           SUM(C.ST_POPULATION_TOTAL) AS ST_POP,
           SUM(P.POPULATION_TOTAL) AS TOTAL_POP
    FROM LOCATIONS L
    JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
    JOIN CENSUS_CASTE C ON P.CENSUS_ID = C.CENSUS_ID
    GROUP BY L.STATE
)
SELECT STATE,
       ROUND(SC_POP * 100.0 / NULLIF(TOTAL_POP, 0), 2) AS SC_PERCENTAGE,
       ROUND(ST_POP * 100.0 / NULLIF(TOTAL_POP, 0), 2) AS ST_PERCENTAGE,
       CASE
           WHEN ST_POP * 100.0 / NULLIF(TOTAL_POP, 0) > 50 THEN 'ST Majority'
           WHEN SC_POP * 100.0 / NULLIF(TOTAL_POP, 0) > 25 THEN 'High SC'
           ELSE 'General'
       END AS DEMOGRAPHIC_CATEGORY
FROM CasteDistribution
ORDER BY ST_PERCENTAGE DESC;"""
    },
    {
        "id": 30,
        "level": 3,
        "category": "Population Analytics",
        "sql": """WITH PopulationStats AS (
    SELECT L.STATE,
           SUM(P.POPULATION_TOTAL) AS POPULATION,
           SUM(P.HOUSEHOLDS) AS HOUSEHOLDS
    FROM LOCATIONS L
    JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
    GROUP BY L.STATE
)
SELECT STATE, POPULATION, HOUSEHOLDS,
       ROUND(POPULATION * 1.0 / NULLIF(HOUSEHOLDS, 0), 2) AS AVG_HOUSEHOLD_SIZE,
       DENSE_RANK() OVER (ORDER BY POPULATION * 1.0 / NULLIF(HOUSEHOLDS, 0) DESC) AS HOUSEHOLD_SIZE_RANK
FROM PopulationStats
WHERE HOUSEHOLDS > 0;"""
    },
    {
        "id": 31,
        "level": 3,
        "category": "Employment Statistics",
        "sql": """WITH OccupationStats AS (
    SELECT L.STATE,
           SUM(M.CULTIVATORS_TOTAL) AS CULTIVATORS,
           SUM(M.AGRI_LABOURERS_TOTAL) AS AGRI_LABOURERS,
           SUM(M.HOUSEHOLD_INDUSTRY_TOTAL) AS HOUSEHOLD_INDUSTRY,
           SUM(M.OTHER_WORKERS_TOTAL) AS OTHER_WORKERS
    FROM LOCATIONS L
    JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
    JOIN CENSUS_MAIN_WORKERS_DETAIL M ON P.CENSUS_ID = M.CENSUS_ID
    GROUP BY L.STATE
)
SELECT STATE,
       CULTIVATORS, AGRI_LABOURERS, HOUSEHOLD_INDUSTRY, OTHER_WORKERS,
       CASE
           WHEN CULTIVATORS + AGRI_LABOURERS > HOUSEHOLD_INDUSTRY + OTHER_WORKERS THEN 'Agricultural'
           ELSE 'Non-Agricultural'
       END AS ECONOMY_TYPE
FROM OccupationStats
ORDER BY CULTIVATORS + AGRI_LABOURERS DESC;"""
    },
    {
        "id": 32,
        "level": 3,
        "category": "Geographic Aggregations",
        "sql": """WITH DistrictPopulation AS (
    SELECT L.STATE, L.DISTRICT,
           SUM(P.POPULATION_TOTAL) AS POPULATION
    FROM LOCATIONS L
    JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
    GROUP BY L.STATE, L.DISTRICT
)
SELECT STATE, DISTRICT, POPULATION,
       SUM(POPULATION) OVER (PARTITION BY STATE) AS STATE_TOTAL,
       ROUND(POPULATION * 100.0 / SUM(POPULATION) OVER (PARTITION BY STATE), 2) AS PCT_OF_STATE
FROM DistrictPopulation
ORDER BY STATE, POPULATION DESC;"""
    },
    {
        "id": 33,
        "level": 3,
        "category": "Literacy Analysis",
        "sql": """WITH GenderLiteracy AS (
    SELECT L.STATE,
           SUM(LIT.LITERATE_MALE) AS MALE_LITERATE,
           SUM(LIT.LITERATE_FEMALE) AS FEMALE_LITERATE,
           SUM(P.POPULATION_MALE) AS MALE_POP,
           SUM(P.POPULATION_FEMALE) AS FEMALE_POP
    FROM LOCATIONS L
    JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
    JOIN CENSUS_LITERACY LIT ON P.CENSUS_ID = LIT.CENSUS_ID
    GROUP BY L.STATE
)
SELECT STATE,
       ROUND(MALE_LITERATE * 100.0 / NULLIF(MALE_POP, 0), 2) AS MALE_LITERACY_RATE,
       ROUND(FEMALE_LITERATE * 100.0 / NULLIF(FEMALE_POP, 0), 2) AS FEMALE_LITERACY_RATE,
       ROUND(MALE_LITERATE * 100.0 / NULLIF(MALE_POP, 0), 2) - ROUND(FEMALE_LITERATE * 100.0 / NULLIF(FEMALE_POP, 0), 2) AS GENDER_GAP
FROM GenderLiteracy
ORDER BY GENDER_GAP DESC;"""
    },
    {
        "id": 34,
        "level": 3,
        "category": "Employment Statistics",
        "sql": """WITH WorkerComparison AS (
    SELECT L.STATE,
           SUM(W.MAIN_WORKERS_TOTAL) AS MAIN_WORKERS,
           SUM(W.MARGINAL_WORKERS_TOTAL) AS MARGINAL_WORKERS
    FROM LOCATIONS L
    JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
    JOIN CENSUS_WORKERS_SUMMARY W ON P.CENSUS_ID = W.CENSUS_ID
    GROUP BY L.STATE
)
SELECT STATE, MAIN_WORKERS, MARGINAL_WORKERS,
       ROUND(MARGINAL_WORKERS * 100.0 / NULLIF(MAIN_WORKERS + MARGINAL_WORKERS, 0), 2) AS MARGINAL_PCT,
       ROW_NUMBER() OVER (ORDER BY MARGINAL_WORKERS * 100.0 / NULLIF(MAIN_WORKERS + MARGINAL_WORKERS, 0) DESC) AS RANK
FROM WorkerComparison;"""
    },
    {
        "id": 35,
        "level": 3,
        "category": "Population Analytics",
        "sql": """WITH UrbanRural AS (
    SELECT L.STATE,
           SUM(CASE WHEN P.RESIDENCE_TYPE = 'Urban' THEN P.POPULATION_TOTAL ELSE 0 END) AS URBAN_POP,
           SUM(CASE WHEN P.RESIDENCE_TYPE = 'Rural' THEN P.POPULATION_TOTAL ELSE 0 END) AS RURAL_POP
    FROM LOCATIONS L
    JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
    GROUP BY L.STATE
)
SELECT STATE, URBAN_POP, RURAL_POP,
       ROUND(URBAN_POP * 100.0 / NULLIF(URBAN_POP + RURAL_POP, 0), 2) AS URBANIZATION_RATE
FROM UrbanRural
WHERE URBAN_POP + RURAL_POP > 0
ORDER BY URBANIZATION_RATE DESC;"""
    },
    {
        "id": 36,
        "level": 3,
        "category": "Caste Demographics",
        "sql": """WITH SCGender AS (
    SELECT L.STATE,
           SUM(C.SC_POPULATION_MALE) AS SC_MALE,
           SUM(C.SC_POPULATION_FEMALE) AS SC_FEMALE,
           SUM(C.ST_POPULATION_MALE) AS ST_MALE,
           SUM(C.ST_POPULATION_FEMALE) AS ST_FEMALE
    FROM LOCATIONS L
    JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
    JOIN CENSUS_CASTE C ON P.CENSUS_ID = C.CENSUS_ID
    GROUP BY L.STATE
)
SELECT STATE,
       ROUND(SC_FEMALE * 1000.0 / NULLIF(SC_MALE, 0), 0) AS SC_SEX_RATIO,
       ROUND(ST_FEMALE * 1000.0 / NULLIF(ST_MALE, 0), 0) AS ST_SEX_RATIO
FROM SCGender
WHERE SC_MALE > 0 OR ST_MALE > 0
ORDER BY SC_SEX_RATIO DESC;"""
    },
    {
        "id": 37,
        "level": 3,
        "category": "Geographic Aggregations",
        "sql": """WITH SubDistrictStats AS (
    SELECT L.STATE, L.DISTRICT, L.SUB_DISTRICT,
           SUM(P.POPULATION_TOTAL) AS POPULATION,
           COUNT(DISTINCT L.VILLAGE_ULB) AS VILLAGE_COUNT
    FROM LOCATIONS L
    JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
    GROUP BY L.STATE, L.DISTRICT, L.SUB_DISTRICT
)
SELECT STATE, DISTRICT, SUB_DISTRICT, POPULATION, VILLAGE_COUNT,
       ROUND(POPULATION * 1.0 / NULLIF(VILLAGE_COUNT, 0), 0) AS AVG_VILLAGE_POPULATION,
       RANK() OVER (PARTITION BY STATE ORDER BY POPULATION DESC) AS RANK_IN_STATE
FROM SubDistrictStats
WHERE VILLAGE_COUNT > 0;"""
    },

    # ==========================================================================
    # LEVEL 4 - ADVANCED (8 queries)
    # Multi-CTE, complex aggregations, subqueries
    # ==========================================================================
    {
        "id": 38,
        "level": 4,
        "category": "Population Analytics",
        "sql": """WITH StateStats AS (
    SELECT L.STATE,
           SUM(P.POPULATION_TOTAL) AS POPULATION,
           SUM(P.HOUSEHOLDS) AS HOUSEHOLDS
    FROM LOCATIONS L
    JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
    GROUP BY L.STATE
),
LiteracyStats AS (
    SELECT L.STATE,
           SUM(LIT.LITERATE_TOTAL) AS LITERATE,
           SUM(LIT.LITERATE_TOTAL + LIT.ILLITERATE_TOTAL) AS ASSESSED
    FROM LOCATIONS L
    JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
    JOIN CENSUS_LITERACY LIT ON P.CENSUS_ID = LIT.CENSUS_ID
    GROUP BY L.STATE
),
WorkerStats AS (
    SELECT L.STATE,
           SUM(W.WORKING_TOTAL) AS WORKERS
    FROM LOCATIONS L
    JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
    JOIN CENSUS_WORKERS_SUMMARY W ON P.CENSUS_ID = W.CENSUS_ID
    GROUP BY L.STATE
)
SELECT S.STATE, S.POPULATION, S.HOUSEHOLDS,
       ROUND(L.LITERATE * 100.0 / NULLIF(L.ASSESSED, 0), 2) AS LITERACY_RATE,
       ROUND(W.WORKERS * 100.0 / NULLIF(S.POPULATION, 0), 2) AS EMPLOYMENT_RATE
FROM StateStats S
JOIN LiteracyStats L ON S.STATE = L.STATE
JOIN WorkerStats W ON S.STATE = W.STATE
ORDER BY S.POPULATION DESC;"""
    },
    {
        "id": 39,
        "level": 4,
        "category": "Caste Demographics",
        "sql": """WITH CasteStats AS (
    SELECT L.STATE, L.DISTRICT,
           SUM(C.SC_POPULATION_TOTAL) AS SC_POP,
           SUM(C.ST_POPULATION_TOTAL) AS ST_POP,
           SUM(P.POPULATION_TOTAL) AS TOTAL_POP
    FROM LOCATIONS L
    JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
    JOIN CENSUS_CASTE C ON P.CENSUS_ID = C.CENSUS_ID
    GROUP BY L.STATE, L.DISTRICT
),
LiteracyStats AS (
    SELECT L.STATE, L.DISTRICT,
           SUM(LIT.LITERATE_TOTAL) AS LITERATE,
           SUM(LIT.LITERATE_TOTAL + LIT.ILLITERATE_TOTAL) AS TOTAL_ASSESSED
    FROM LOCATIONS L
    JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
    JOIN CENSUS_LITERACY LIT ON P.CENSUS_ID = LIT.CENSUS_ID
    GROUP BY L.STATE, L.DISTRICT
)
SELECT CS.STATE, CS.DISTRICT,
       ROUND((CS.SC_POP + CS.ST_POP) * 100.0 / NULLIF(CS.TOTAL_POP, 0), 2) AS SC_ST_PCT,
       ROUND(LS.LITERATE * 100.0 / NULLIF(LS.TOTAL_ASSESSED, 0), 2) AS LITERACY_RATE
FROM CasteStats CS
JOIN LiteracyStats LS ON CS.STATE = LS.STATE AND CS.DISTRICT = LS.DISTRICT
WHERE CS.TOTAL_POP > 10000
ORDER BY SC_ST_PCT DESC
LIMIT 30;"""
    },
    {
        "id": 40,
        "level": 4,
        "category": "Employment Statistics",
        "sql": """WITH MainWorkers AS (
    SELECT L.STATE,
           SUM(M.CULTIVATORS_TOTAL) AS MAIN_CULTIVATORS,
           SUM(M.AGRI_LABOURERS_TOTAL) AS MAIN_AGRI_LAB,
           SUM(M.HOUSEHOLD_INDUSTRY_TOTAL) AS MAIN_HH_IND,
           SUM(M.OTHER_WORKERS_TOTAL) AS MAIN_OTHER
    FROM LOCATIONS L
    JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
    JOIN CENSUS_MAIN_WORKERS_DETAIL M ON P.CENSUS_ID = M.CENSUS_ID
    GROUP BY L.STATE
),
MarginalWorkers AS (
    SELECT L.STATE,
           SUM(MG.CULTIVATORS_TOTAL) AS MARG_CULTIVATORS,
           SUM(MG.AGRI_LABOURERS_TOTAL) AS MARG_AGRI_LAB,
           SUM(MG.HOUSEHOLD_INDUSTRY_TOTAL) AS MARG_HH_IND,
           SUM(MG.OTHER_WORKERS_TOTAL) AS MARG_OTHER
    FROM LOCATIONS L
    JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
    JOIN CENSUS_MARGINAL_WORKERS_DETAIL MG ON P.CENSUS_ID = MG.CENSUS_ID
    GROUP BY L.STATE
)
SELECT MW.STATE,
       MW.MAIN_CULTIVATORS + MG.MARG_CULTIVATORS AS TOTAL_CULTIVATORS,
       MW.MAIN_AGRI_LAB + MG.MARG_AGRI_LAB AS TOTAL_AGRI_LABOURERS,
       MW.MAIN_HH_IND + MG.MARG_HH_IND AS TOTAL_HOUSEHOLD_INDUSTRY,
       MW.MAIN_OTHER + MG.MARG_OTHER AS TOTAL_OTHER_WORKERS,
       ROUND(MG.MARG_CULTIVATORS * 100.0 / NULLIF(MW.MAIN_CULTIVATORS + MG.MARG_CULTIVATORS, 0), 2) AS MARGINAL_CULTIVATOR_PCT
FROM MainWorkers MW
JOIN MarginalWorkers MG ON MW.STATE = MG.STATE
ORDER BY TOTAL_CULTIVATORS DESC;"""
    },
    {
        "id": 41,
        "level": 4,
        "category": "Literacy Analysis",
        "sql": """WITH RuralLiteracy AS (
    SELECT L.STATE,
           SUM(LIT.LITERATE_MALE) AS RURAL_MALE_LIT,
           SUM(LIT.LITERATE_FEMALE) AS RURAL_FEMALE_LIT,
           SUM(P.POPULATION_MALE) AS RURAL_MALE_POP,
           SUM(P.POPULATION_FEMALE) AS RURAL_FEMALE_POP
    FROM LOCATIONS L
    JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
    JOIN CENSUS_LITERACY LIT ON P.CENSUS_ID = LIT.CENSUS_ID
    WHERE P.RESIDENCE_TYPE = 'Rural'
    GROUP BY L.STATE
),
UrbanLiteracy AS (
    SELECT L.STATE,
           SUM(LIT.LITERATE_MALE) AS URBAN_MALE_LIT,
           SUM(LIT.LITERATE_FEMALE) AS URBAN_FEMALE_LIT,
           SUM(P.POPULATION_MALE) AS URBAN_MALE_POP,
           SUM(P.POPULATION_FEMALE) AS URBAN_FEMALE_POP
    FROM LOCATIONS L
    JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
    JOIN CENSUS_LITERACY LIT ON P.CENSUS_ID = LIT.CENSUS_ID
    WHERE P.RESIDENCE_TYPE = 'Urban'
    GROUP BY L.STATE
)
SELECT R.STATE,
       ROUND(R.RURAL_MALE_LIT * 100.0 / NULLIF(R.RURAL_MALE_POP, 0), 2) AS RURAL_MALE_LITERACY,
       ROUND(R.RURAL_FEMALE_LIT * 100.0 / NULLIF(R.RURAL_FEMALE_POP, 0), 2) AS RURAL_FEMALE_LITERACY,
       ROUND(U.URBAN_MALE_LIT * 100.0 / NULLIF(U.URBAN_MALE_POP, 0), 2) AS URBAN_MALE_LITERACY,
       ROUND(U.URBAN_FEMALE_LIT * 100.0 / NULLIF(U.URBAN_FEMALE_POP, 0), 2) AS URBAN_FEMALE_LITERACY
FROM RuralLiteracy R
LEFT JOIN UrbanLiteracy U ON R.STATE = U.STATE
ORDER BY R.STATE;"""
    },
    {
        "id": 42,
        "level": 4,
        "category": "Geographic Aggregations",
        "sql": """WITH DistrictStats AS (
    SELECT L.STATE, L.DISTRICT,
           SUM(P.POPULATION_TOTAL) AS POPULATION,
           COUNT(DISTINCT L.SUB_DISTRICT) AS SUB_DISTRICTS,
           COUNT(DISTINCT L.VILLAGE_ULB) AS VILLAGES
    FROM LOCATIONS L
    JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
    GROUP BY L.STATE, L.DISTRICT
),
StateAvg AS (
    SELECT STATE,
           AVG(POPULATION) AS AVG_DISTRICT_POP,
           AVG(VILLAGES) AS AVG_VILLAGES
    FROM DistrictStats
    GROUP BY STATE
)
SELECT DS.STATE, DS.DISTRICT, DS.POPULATION, DS.VILLAGES,
       ROUND(DS.POPULATION * 1.0 / SA.AVG_DISTRICT_POP, 2) AS POP_VS_STATE_AVG,
       CASE
           WHEN DS.POPULATION > SA.AVG_DISTRICT_POP * 1.5 THEN 'Large'
           WHEN DS.POPULATION < SA.AVG_DISTRICT_POP * 0.5 THEN 'Small'
           ELSE 'Medium'
       END AS DISTRICT_SIZE
FROM DistrictStats DS
JOIN StateAvg SA ON DS.STATE = SA.STATE
ORDER BY DS.POPULATION DESC;"""
    },
    {
        "id": 43,
        "level": 4,
        "category": "Employment Statistics",
        "sql": """WITH GenderWorkers AS (
    SELECT L.STATE,
           SUM(W.WORKING_MALE) AS MALE_WORKERS,
           SUM(W.WORKING_FEMALE) AS FEMALE_WORKERS,
           SUM(P.POPULATION_MALE) AS MALE_POP,
           SUM(P.POPULATION_FEMALE) AS FEMALE_POP
    FROM LOCATIONS L
    JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
    JOIN CENSUS_WORKERS_SUMMARY W ON P.CENSUS_ID = W.CENSUS_ID
    GROUP BY L.STATE
),
WorkerRates AS (
    SELECT STATE,
           ROUND(MALE_WORKERS * 100.0 / NULLIF(MALE_POP, 0), 2) AS MALE_WORK_RATE,
           ROUND(FEMALE_WORKERS * 100.0 / NULLIF(FEMALE_POP, 0), 2) AS FEMALE_WORK_RATE
    FROM GenderWorkers
)
SELECT STATE, MALE_WORK_RATE, FEMALE_WORK_RATE,
       MALE_WORK_RATE - FEMALE_WORK_RATE AS GENDER_GAP,
       RANK() OVER (ORDER BY MALE_WORK_RATE - FEMALE_WORK_RATE DESC) AS GAP_RANK
FROM WorkerRates
ORDER BY GENDER_GAP DESC;"""
    },
    {
        "id": 44,
        "level": 4,
        "category": "Caste Demographics",
        "sql": """WITH SCStats AS (
    SELECT L.STATE,
           SUM(C.SC_POPULATION_MALE) AS SC_MALE,
           SUM(C.SC_POPULATION_FEMALE) AS SC_FEMALE,
           SUM(C.SC_POPULATION_TOTAL) AS SC_TOTAL
    FROM LOCATIONS L
    JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
    JOIN CENSUS_CASTE C ON P.CENSUS_ID = C.CENSUS_ID
    GROUP BY L.STATE
),
SCLiteracy AS (
    SELECT L.STATE,
           SUM(LIT.LITERATE_TOTAL) AS LITERATE
    FROM LOCATIONS L
    JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
    JOIN CENSUS_LITERACY LIT ON P.CENSUS_ID = LIT.CENSUS_ID
    JOIN CENSUS_CASTE C ON P.CENSUS_ID = C.CENSUS_ID
    WHERE C.SC_POPULATION_TOTAL > 0
    GROUP BY L.STATE
),
TotalPop AS (
    SELECT L.STATE, SUM(P.POPULATION_TOTAL) AS TOTAL
    FROM LOCATIONS L
    JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
    GROUP BY L.STATE
)
SELECT SC.STATE, SC.SC_TOTAL,
       ROUND(SC.SC_TOTAL * 100.0 / NULLIF(TP.TOTAL, 0), 2) AS SC_PCT,
       ROUND(SC.SC_FEMALE * 1000.0 / NULLIF(SC.SC_MALE, 0), 0) AS SC_SEX_RATIO
FROM SCStats SC
JOIN TotalPop TP ON SC.STATE = TP.STATE
WHERE SC.SC_TOTAL > 0
ORDER BY SC_PCT DESC;"""
    },
    {
        "id": 45,
        "level": 4,
        "category": "Population Analytics",
        "sql": """WITH ChildPopulation AS (
    SELECT L.STATE, L.DISTRICT,
           SUM(P.POPULATION_0_6_TOTAL) AS CHILDREN,
           SUM(P.POPULATION_0_6_MALE) AS CHILDREN_MALE,
           SUM(P.POPULATION_0_6_FEMALE) AS CHILDREN_FEMALE,
           SUM(P.POPULATION_TOTAL) AS TOTAL_POP
    FROM LOCATIONS L
    JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
    GROUP BY L.STATE, L.DISTRICT
),
ChildStats AS (
    SELECT STATE, DISTRICT, CHILDREN, TOTAL_POP,
           ROUND(CHILDREN * 100.0 / NULLIF(TOTAL_POP, 0), 2) AS CHILD_PCT,
           ROUND(CHILDREN_FEMALE * 1000.0 / NULLIF(CHILDREN_MALE, 0), 0) AS CHILD_SEX_RATIO
    FROM ChildPopulation
)
SELECT STATE, DISTRICT, CHILDREN, CHILD_PCT, CHILD_SEX_RATIO,
       AVG(CHILD_SEX_RATIO) OVER (PARTITION BY STATE) AS STATE_AVG_CHILD_SEX_RATIO,
       CHILD_SEX_RATIO - AVG(CHILD_SEX_RATIO) OVER (PARTITION BY STATE) AS DEVIATION_FROM_STATE_AVG
FROM ChildStats
WHERE CHILDREN > 1000
ORDER BY CHILD_SEX_RATIO ASC;"""
    },

    # ==========================================================================
    # LEVEL 5 - COMPLEX (5 queries)
    # Statistical calculations, rankings, multiple comparisons
    # ==========================================================================
    {
        "id": 46,
        "level": 5,
        "category": "Employment Statistics",
        "sql": """WITH StateWorkerStats AS (
    SELECT L.STATE,
           SUM(W.WORKING_MALE) AS MALE_WORKERS,
           SUM(W.WORKING_FEMALE) AS FEMALE_WORKERS,
           SUM(P.POPULATION_MALE) AS MALE_POP,
           SUM(P.POPULATION_FEMALE) AS FEMALE_POP
    FROM LOCATIONS L
    JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
    JOIN CENSUS_WORKERS_SUMMARY W ON P.CENSUS_ID = W.CENSUS_ID
    GROUP BY L.STATE
),
WorkerRates AS (
    SELECT STATE,
           ROUND(MALE_WORKERS * 100.0 / NULLIF(MALE_POP, 0), 2) AS MALE_WORK_RATE,
           ROUND(FEMALE_WORKERS * 100.0 / NULLIF(FEMALE_POP, 0), 2) AS FEMALE_WORK_RATE
    FROM StateWorkerStats
),
RateComparison AS (
    SELECT STATE, MALE_WORK_RATE, FEMALE_WORK_RATE,
           MALE_WORK_RATE - FEMALE_WORK_RATE AS GENDER_GAP,
           AVG(MALE_WORK_RATE - FEMALE_WORK_RATE) OVER () AS AVG_GAP,
           STDDEV(MALE_WORK_RATE - FEMALE_WORK_RATE) OVER () AS STD_GAP
    FROM WorkerRates
)
SELECT STATE, MALE_WORK_RATE, FEMALE_WORK_RATE, GENDER_GAP,
       ROUND(AVG_GAP, 2) AS NATIONAL_AVG_GAP,
       CASE
           WHEN GENDER_GAP > AVG_GAP + STD_GAP THEN 'Significantly Above Average'
           WHEN GENDER_GAP > AVG_GAP THEN 'Above Average'
           WHEN GENDER_GAP < AVG_GAP - STD_GAP THEN 'Significantly Below Average'
           ELSE 'Below Average'
       END AS GAP_CATEGORY
FROM RateComparison
ORDER BY GENDER_GAP DESC;"""
    },
    {
        "id": 47,
        "level": 5,
        "category": "Literacy Analysis",
        "sql": """WITH DistrictMetrics AS (
    SELECT L.STATE, L.DISTRICT,
           SUM(P.POPULATION_TOTAL) AS POPULATION,
           SUM(LIT.LITERATE_TOTAL) AS LITERATE,
           SUM(LIT.LITERATE_TOTAL + LIT.ILLITERATE_TOTAL) AS ASSESSED,
           SUM(C.SC_POPULATION_TOTAL + C.ST_POPULATION_TOTAL) AS SC_ST_POP
    FROM LOCATIONS L
    JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
    JOIN CENSUS_LITERACY LIT ON P.CENSUS_ID = LIT.CENSUS_ID
    JOIN CENSUS_CASTE C ON P.CENSUS_ID = C.CENSUS_ID
    GROUP BY L.STATE, L.DISTRICT
),
DistrictRates AS (
    SELECT STATE, DISTRICT, POPULATION,
           ROUND(LITERATE * 100.0 / NULLIF(ASSESSED, 0), 2) AS LITERACY_RATE,
           ROUND(SC_ST_POP * 100.0 / NULLIF(POPULATION, 0), 2) AS SC_ST_PCT
    FROM DistrictMetrics
    WHERE POPULATION > 10000
),
Quartiles AS (
    SELECT STATE, DISTRICT, POPULATION, LITERACY_RATE, SC_ST_PCT,
           NTILE(4) OVER (ORDER BY LITERACY_RATE) AS LITERACY_QUARTILE,
           NTILE(4) OVER (ORDER BY SC_ST_PCT DESC) AS SC_ST_QUARTILE
    FROM DistrictRates
)
SELECT STATE, DISTRICT, LITERACY_RATE, SC_ST_PCT,
       CASE LITERACY_QUARTILE
           WHEN 1 THEN 'Low Literacy'
           WHEN 2 THEN 'Below Average Literacy'
           WHEN 3 THEN 'Above Average Literacy'
           WHEN 4 THEN 'High Literacy'
       END AS LITERACY_CATEGORY,
       CASE SC_ST_QUARTILE
           WHEN 1 THEN 'High SC/ST'
           WHEN 2 THEN 'Above Average SC/ST'
           WHEN 3 THEN 'Below Average SC/ST'
           WHEN 4 THEN 'Low SC/ST'
       END AS SC_ST_CATEGORY
FROM Quartiles
ORDER BY LITERACY_RATE DESC;"""
    },
    {
        "id": 48,
        "level": 5,
        "category": "Geographic Aggregations",
        "sql": """WITH VillageStats AS (
    SELECT L.STATE, L.DISTRICT, L.SUB_DISTRICT, L.VILLAGE_ULB,
           SUM(P.POPULATION_TOTAL) AS POPULATION,
           SUM(P.HOUSEHOLDS) AS HOUSEHOLDS
    FROM LOCATIONS L
    JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
    WHERE L.LOCATION_LEVEL = 'VILLAGE'
    GROUP BY L.STATE, L.DISTRICT, L.SUB_DISTRICT, L.VILLAGE_ULB
),
SubDistrictAgg AS (
    SELECT STATE, DISTRICT, SUB_DISTRICT,
           COUNT(*) AS VILLAGE_COUNT,
           SUM(POPULATION) AS TOTAL_POP,
           AVG(POPULATION) AS AVG_VILLAGE_POP,
           MIN(POPULATION) AS MIN_VILLAGE_POP,
           MAX(POPULATION) AS MAX_VILLAGE_POP
    FROM VillageStats
    GROUP BY STATE, DISTRICT, SUB_DISTRICT
),
DistrictSummary AS (
    SELECT STATE, DISTRICT,
           SUM(VILLAGE_COUNT) AS TOTAL_VILLAGES,
           SUM(TOTAL_POP) AS DISTRICT_POP,
           AVG(AVG_VILLAGE_POP) AS AVG_VILLAGE_SIZE
    FROM SubDistrictAgg
    GROUP BY STATE, DISTRICT
)
SELECT SD.STATE, SD.DISTRICT, SD.SUB_DISTRICT,
       SD.VILLAGE_COUNT, SD.TOTAL_POP,
       ROUND(SD.AVG_VILLAGE_POP, 0) AS AVG_VILLAGE_POP,
       ROUND(SD.TOTAL_POP * 100.0 / DS.DISTRICT_POP, 2) AS PCT_OF_DISTRICT,
       RANK() OVER (PARTITION BY SD.STATE, SD.DISTRICT ORDER BY SD.TOTAL_POP DESC) AS RANK_IN_DISTRICT
FROM SubDistrictAgg SD
JOIN DistrictSummary DS ON SD.STATE = DS.STATE AND SD.DISTRICT = DS.DISTRICT
ORDER BY SD.STATE, SD.DISTRICT, RANK_IN_DISTRICT;"""
    },
    {
        "id": 49,
        "level": 5,
        "category": "Caste Demographics",
        "sql": """WITH StateMetrics AS (
    SELECT L.STATE,
           SUM(P.POPULATION_TOTAL) AS TOTAL_POP,
           SUM(C.SC_POPULATION_TOTAL) AS SC_POP,
           SUM(C.ST_POPULATION_TOTAL) AS ST_POP,
           SUM(LIT.LITERATE_TOTAL) AS LITERATE,
           SUM(LIT.LITERATE_TOTAL + LIT.ILLITERATE_TOTAL) AS ASSESSED,
           SUM(W.WORKING_TOTAL) AS WORKERS
    FROM LOCATIONS L
    JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
    JOIN CENSUS_CASTE C ON P.CENSUS_ID = C.CENSUS_ID
    JOIN CENSUS_LITERACY LIT ON P.CENSUS_ID = LIT.CENSUS_ID
    JOIN CENSUS_WORKERS_SUMMARY W ON P.CENSUS_ID = W.CENSUS_ID
    GROUP BY L.STATE
),
StateRates AS (
    SELECT STATE, TOTAL_POP,
           ROUND(SC_POP * 100.0 / NULLIF(TOTAL_POP, 0), 2) AS SC_PCT,
           ROUND(ST_POP * 100.0 / NULLIF(TOTAL_POP, 0), 2) AS ST_PCT,
           ROUND(LITERATE * 100.0 / NULLIF(ASSESSED, 0), 2) AS LITERACY_RATE,
           ROUND(WORKERS * 100.0 / NULLIF(TOTAL_POP, 0), 2) AS WORK_RATE
    FROM StateMetrics
),
Rankings AS (
    SELECT STATE, TOTAL_POP, SC_PCT, ST_PCT, LITERACY_RATE, WORK_RATE,
           RANK() OVER (ORDER BY SC_PCT DESC) AS SC_RANK,
           RANK() OVER (ORDER BY ST_PCT DESC) AS ST_RANK,
           RANK() OVER (ORDER BY LITERACY_RATE DESC) AS LITERACY_RANK,
           RANK() OVER (ORDER BY WORK_RATE DESC) AS WORK_RANK
    FROM StateRates
)
SELECT STATE, SC_PCT, ST_PCT, LITERACY_RATE, WORK_RATE,
       SC_RANK, ST_RANK, LITERACY_RANK, WORK_RANK,
       (SC_RANK + ST_RANK + LITERACY_RANK + WORK_RANK) / 4.0 AS COMPOSITE_RANK
FROM Rankings
ORDER BY COMPOSITE_RANK;"""
    },
    {
        "id": 50,
        "level": 5,
        "category": "Employment Statistics",
        "sql": """WITH OccupationBreakdown AS (
    SELECT L.STATE,
           SUM(MW.CULTIVATORS_TOTAL) + SUM(MG.CULTIVATORS_TOTAL) AS CULTIVATORS,
           SUM(MW.AGRI_LABOURERS_TOTAL) + SUM(MG.AGRI_LABOURERS_TOTAL) AS AGRI_LABOURERS,
           SUM(MW.HOUSEHOLD_INDUSTRY_TOTAL) + SUM(MG.HOUSEHOLD_INDUSTRY_TOTAL) AS HOUSEHOLD_INDUSTRY,
           SUM(MW.OTHER_WORKERS_TOTAL) + SUM(MG.OTHER_WORKERS_TOTAL) AS OTHER_WORKERS,
           SUM(WS.WORKING_TOTAL) AS TOTAL_WORKERS
    FROM LOCATIONS L
    JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
    JOIN CENSUS_MAIN_WORKERS_DETAIL MW ON P.CENSUS_ID = MW.CENSUS_ID
    JOIN CENSUS_MARGINAL_WORKERS_DETAIL MG ON P.CENSUS_ID = MG.CENSUS_ID
    JOIN CENSUS_WORKERS_SUMMARY WS ON P.CENSUS_ID = WS.CENSUS_ID
    GROUP BY L.STATE
),
OccupationPct AS (
    SELECT STATE,
           ROUND(CULTIVATORS * 100.0 / NULLIF(TOTAL_WORKERS, 0), 2) AS CULTIVATOR_PCT,
           ROUND(AGRI_LABOURERS * 100.0 / NULLIF(TOTAL_WORKERS, 0), 2) AS AGRI_LAB_PCT,
           ROUND(HOUSEHOLD_INDUSTRY * 100.0 / NULLIF(TOTAL_WORKERS, 0), 2) AS HH_IND_PCT,
           ROUND(OTHER_WORKERS * 100.0 / NULLIF(TOTAL_WORKERS, 0), 2) AS OTHER_PCT,
           CULTIVATORS + AGRI_LABOURERS AS AGRICULTURAL_WORKERS,
           HOUSEHOLD_INDUSTRY + OTHER_WORKERS AS NON_AGRICULTURAL_WORKERS,
           TOTAL_WORKERS
    FROM OccupationBreakdown
),
EconomyClassification AS (
    SELECT STATE, CULTIVATOR_PCT, AGRI_LAB_PCT, HH_IND_PCT, OTHER_PCT,
           ROUND(AGRICULTURAL_WORKERS * 100.0 / NULLIF(TOTAL_WORKERS, 0), 2) AS AGRI_SECTOR_PCT,
           ROUND(NON_AGRICULTURAL_WORKERS * 100.0 / NULLIF(TOTAL_WORKERS, 0), 2) AS NON_AGRI_SECTOR_PCT,
           CASE
               WHEN AGRICULTURAL_WORKERS > NON_AGRICULTURAL_WORKERS * 2 THEN 'Highly Agricultural'
               WHEN AGRICULTURAL_WORKERS > NON_AGRICULTURAL_WORKERS THEN 'Agricultural'
               WHEN NON_AGRICULTURAL_WORKERS > AGRICULTURAL_WORKERS * 2 THEN 'Highly Non-Agricultural'
               ELSE 'Mixed Economy'
           END AS ECONOMY_TYPE
    FROM OccupationPct
),
NationalAvg AS (
    SELECT AVG(AGRI_SECTOR_PCT) AS NAT_AGRI_PCT
    FROM EconomyClassification
)
SELECT EC.STATE, EC.CULTIVATOR_PCT, EC.AGRI_LAB_PCT, EC.HH_IND_PCT, EC.OTHER_PCT,
       EC.AGRI_SECTOR_PCT, EC.NON_AGRI_SECTOR_PCT, EC.ECONOMY_TYPE,
       ROUND(NA.NAT_AGRI_PCT, 2) AS NATIONAL_AGRI_AVG,
       ROUND(EC.AGRI_SECTOR_PCT - NA.NAT_AGRI_PCT, 2) AS DEVIATION_FROM_NATIONAL
FROM EconomyClassification EC
CROSS JOIN NationalAvg NA
ORDER BY EC.AGRI_SECTOR_PCT DESC;"""
    },
]


def generate_query_files(output_dir: str = "queries"):
    """
    Generate individual SQL files for each query.

    Args:
        output_dir: Directory to write SQL files to
    """
    output_path = Path(output_dir)
    output_path.mkdir(exist_ok=True)

    level_names = {
        1: "Simple",
        2: "Moderate",
        3: "Intermediate",
        4: "Advanced",
        5: "Complex"
    }

    for query in QUERIES:
        query_id = query["id"]
        level = query["level"]
        category = query["category"]
        sql = query["sql"]

        # Create filename
        filename = f"indicdb_{query_id:03d}.sql"
        filepath = output_path / filename

        # Create file content with header comment
        content = f"""-- Complexity: Level {level} ({level_names[level]})
-- Category: {category}
{sql}
"""

        # Write file
        with open(filepath, 'w') as f:
            f.write(content)

        print(f"Generated: {filename}")

    print(f"\nTotal queries generated: {len(QUERIES)}")
    print(f"Output directory: {output_path.absolute()}")

    # Print summary by level
    print("\nSummary by complexity level:")
    for level in range(1, 6):
        count = sum(1 for q in QUERIES if q["level"] == level)
        print(f"  Level {level} ({level_names[level]}): {count} queries")


def main():
    """Main entry point."""
    # Get the project root directory
    script_dir = Path(__file__).parent
    project_root = script_dir.parent
    output_dir = project_root / "queries"

    generate_query_files(str(output_dir))


if __name__ == "__main__":
    main()
