-- Complexity: Level 2 (Moderate)
-- Category: Population Analytics
SELECT L.STATE,
       SUM(P.POPULATION_MALE) AS MALE,
       SUM(P.POPULATION_FEMALE) AS FEMALE,
       ROUND(SUM(P.POPULATION_FEMALE) * 1000.0 / NULLIF(SUM(P.POPULATION_MALE), 0), 0) AS SEX_RATIO
FROM LOCATIONS L
JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
GROUP BY L.STATE
ORDER BY SEX_RATIO DESC;
