-- Complexity: Level 4 (Advanced)
-- Category: Caste Demographics
WITH CasteStats AS (
    SELECT L.STATE, L.DISTRICT,
           SUM(C.SC_POPULATION_TOTAL) AS SC_POP,
           SUM(C.ST_POPULATION_TOTAL) AS ST_POP,
           SUM(P.POPULATION_TOTAL) AS TOTAL_POP
    FROM LOCATIONS L
    JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
    JOIN CENSUS_CASTE C ON P.CENSUS_ID = C.CENSUS_ID
    GROUP BY L.STATE, L.DISTRICT
),
LiteracyStats AS (
    SELECT L.STATE, L.DISTRICT,
           SUM(LIT.LITERATE_TOTAL) AS LITERATE,
           SUM(LIT.LITERATE_TOTAL + LIT.ILLITERATE_TOTAL) AS TOTAL_ASSESSED
    FROM LOCATIONS L
    JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
    JOIN CENSUS_LITERACY LIT ON P.CENSUS_ID = LIT.CENSUS_ID
    GROUP BY L.STATE, L.DISTRICT
)
SELECT CS.STATE, CS.DISTRICT,
       ROUND((CS.SC_POP + CS.ST_POP) * 100.0 / NULLIF(CS.TOTAL_POP, 0), 2) AS SC_ST_PCT,
       ROUND(LS.LITERATE * 100.0 / NULLIF(LS.TOTAL_ASSESSED, 0), 2) AS LITERACY_RATE
FROM CasteStats CS
JOIN LiteracyStats LS ON CS.STATE = LS.STATE AND CS.DISTRICT = LS.DISTRICT
WHERE CS.TOTAL_POP > 10000
ORDER BY SC_ST_PCT DESC
LIMIT 30;
