-- Complexity: Level 3 (Intermediate)
-- Category: Employment Statistics
WITH OccupationStats AS (
    SELECT L.STATE,
           SUM(M.CULTIVATORS_TOTAL) AS CULTIVATORS,
           SUM(M.AGRI_LABOURERS_TOTAL) AS AGRI_LABOURERS,
           SUM(M.HOUSEHOLD_INDUSTRY_TOTAL) AS HOUSEHOLD_INDUSTRY,
           SUM(M.OTHER_WORKERS_TOTAL) AS OTHER_WORKERS
    FROM LOCATIONS L
    JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
    JOIN CENSUS_MAIN_WORKERS_DETAIL M ON P.CENSUS_ID = M.CENSUS_ID
    GROUP BY L.STATE
)
SELECT STATE,
       CULTIVATORS, AGRI_LABOURERS, HOUSEHOLD_INDUSTRY, OTHER_WORKERS,
       CASE
           WHEN CULTIVATORS + AGRI_LABOURERS > HOUSEHOLD_INDUSTRY + OTHER_WORKERS THEN 'Agricultural'
           ELSE 'Non-Agricultural'
       END AS ECONOMY_TYPE
FROM OccupationStats
ORDER BY CULTIVATORS + AGRI_LABOURERS DESC;
