-- Complexity: Level 3 (Intermediate)
-- Category: Population Analytics
WITH PopulationStats AS (
    SELECT L.STATE,
           SUM(P.POPULATION_TOTAL) AS POPULATION,
           SUM(P.HOUSEHOLDS) AS HOUSEHOLDS
    FROM LOCATIONS L
    JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
    GROUP BY L.STATE
)
SELECT STATE, POPULATION, HOUSEHOLDS,
       ROUND(POPULATION * 1.0 / NULLIF(HOUSEHOLDS, 0), 2) AS AVG_HOUSEHOLD_SIZE,
       DENSE_RANK() OVER (ORDER BY POPULATION * 1.0 / NULLIF(HOUSEHOLDS, 0) DESC) AS HOUSEHOLD_SIZE_RANK
FROM PopulationStats
WHERE HOUSEHOLDS > 0;
