-- Complexity: Level 3 (Intermediate)
-- Category: Employment Statistics
WITH WorkerStats AS (
    SELECT L.STATE, L.DISTRICT,
           SUM(W.WORKING_MALE) AS MALE_WORKERS,
           SUM(W.WORKING_FEMALE) AS FEMALE_WORKERS,
           SUM(W.WORKING_TOTAL) AS TOTAL_WORKERS
    FROM LOCATIONS L
    JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
    JOIN CENSUS_WORKERS_SUMMARY W ON P.CENSUS_ID = W.CENSUS_ID
    GROUP BY L.STATE, L.DISTRICT
)
SELECT STATE, DISTRICT,
       TOTAL_WORKERS,
       ROUND(FEMALE_WORKERS * 100.0 / NULLIF(TOTAL_WORKERS, 0), 2) AS FEMALE_WORKER_PCT,
       CASE
           WHEN FEMALE_WORKERS * 100.0 / NULLIF(TOTAL_WORKERS, 0) >= 40 THEN 'High'
           WHEN FEMALE_WORKERS * 100.0 / NULLIF(TOTAL_WORKERS, 0) >= 25 THEN 'Medium'
           ELSE 'Low'
       END AS FEMALE_PARTICIPATION_LEVEL
FROM WorkerStats
WHERE TOTAL_WORKERS > 1000
ORDER BY FEMALE_WORKER_PCT DESC;
