-- Complexity: Level 4 (Advanced)
-- Category: Population Analytics
WITH StateStats AS (
    SELECT L.STATE,
           SUM(P.POPULATION_TOTAL) AS POPULATION,
           SUM(P.HOUSEHOLDS) AS HOUSEHOLDS
    FROM LOCATIONS L
    JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
    GROUP BY L.STATE
),
LiteracyStats AS (
    SELECT L.STATE,
           SUM(LIT.LITERATE_TOTAL) AS LITERATE,
           SUM(LIT.LITERATE_TOTAL + LIT.ILLITERATE_TOTAL) AS ASSESSED
    FROM LOCATIONS L
    JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
    JOIN CENSUS_LITERACY LIT ON P.CENSUS_ID = LIT.CENSUS_ID
    GROUP BY L.STATE
),
WorkerStats AS (
    SELECT L.STATE,
           SUM(W.WORKING_TOTAL) AS WORKERS
    FROM LOCATIONS L
    JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
    JOIN CENSUS_WORKERS_SUMMARY W ON P.CENSUS_ID = W.CENSUS_ID
    GROUP BY L.STATE
)
SELECT S.STATE, S.POPULATION, S.HOUSEHOLDS,
       ROUND(L.LITERATE * 100.0 / NULLIF(L.ASSESSED, 0), 2) AS LITERACY_RATE,
       ROUND(W.WORKERS * 100.0 / NULLIF(S.POPULATION, 0), 2) AS EMPLOYMENT_RATE
FROM StateStats S
JOIN LiteracyStats L ON S.STATE = L.STATE
JOIN WorkerStats W ON S.STATE = W.STATE
ORDER BY S.POPULATION DESC;
