-- Complexity: Level 2 (Moderate)
-- Category: Literacy Analysis
SELECT L.STATE,
       SUM(LIT.LITERATE_TOTAL) AS LITERATE,
       SUM(LIT.ILLITERATE_TOTAL) AS ILLITERATE,
       ROUND(SUM(LIT.LITERATE_TOTAL) * 100.0 / NULLIF(SUM(LIT.LITERATE_TOTAL + LIT.ILLITERATE_TOTAL), 0), 2) AS LITERACY_RATE
FROM LOCATIONS L
JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
JOIN CENSUS_LITERACY LIT ON P.CENSUS_ID = LIT.CENSUS_ID
GROUP BY L.STATE
ORDER BY LITERACY_RATE DESC;
