-- Complexity: Level 3 (Intermediate)
-- Category: Literacy Analysis
WITH DistrictLiteracy AS (
    SELECT L.STATE, L.DISTRICT,
           SUM(LIT.LITERATE_TOTAL) AS LITERATE,
           SUM(LIT.LITERATE_TOTAL + LIT.ILLITERATE_TOTAL) AS TOTAL
    FROM LOCATIONS L
    JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
    JOIN CENSUS_LITERACY LIT ON P.CENSUS_ID = LIT.CENSUS_ID
    GROUP BY L.STATE, L.DISTRICT
)
SELECT STATE, DISTRICT,
       ROUND(LITERATE * 100.0 / NULLIF(TOTAL, 0), 2) AS LITERACY_RATE,
       RANK() OVER (PARTITION BY STATE ORDER BY LITERATE * 100.0 / NULLIF(TOTAL, 0) DESC) AS RANK_IN_STATE
FROM DistrictLiteracy
WHERE TOTAL > 0;
