-- Complexity: Level 4 (Advanced)
-- Category: Employment Statistics
WITH GenderWorkers AS (
    SELECT L.STATE,
           SUM(W.WORKING_MALE) AS MALE_WORKERS,
           SUM(W.WORKING_FEMALE) AS FEMALE_WORKERS,
           SUM(P.POPULATION_MALE) AS MALE_POP,
           SUM(P.POPULATION_FEMALE) AS FEMALE_POP
    FROM LOCATIONS L
    JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
    JOIN CENSUS_WORKERS_SUMMARY W ON P.CENSUS_ID = W.CENSUS_ID
    GROUP BY L.STATE
),
WorkerRates AS (
    SELECT STATE,
           ROUND(MALE_WORKERS * 100.0 / NULLIF(MALE_POP, 0), 2) AS MALE_WORK_RATE,
           ROUND(FEMALE_WORKERS * 100.0 / NULLIF(FEMALE_POP, 0), 2) AS FEMALE_WORK_RATE
    FROM GenderWorkers
)
SELECT STATE, MALE_WORK_RATE, FEMALE_WORK_RATE,
       MALE_WORK_RATE - FEMALE_WORK_RATE AS GENDER_GAP,
       RANK() OVER (ORDER BY MALE_WORK_RATE - FEMALE_WORK_RATE DESC) AS GAP_RANK
FROM WorkerRates
ORDER BY GENDER_GAP DESC;
