-- Complexity: Level 5 (Complex)
-- Category: Geographic Aggregations
WITH VillageStats AS (
    SELECT L.STATE, L.DISTRICT, L.SUB_DISTRICT, L.VILLAGE_ULB,
           SUM(P.POPULATION_TOTAL) AS POPULATION,
           SUM(P.HOUSEHOLDS) AS HOUSEHOLDS
    FROM LOCATIONS L
    JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
    WHERE L.LOCATION_LEVEL = 'VILLAGE'
    GROUP BY L.STATE, L.DISTRICT, L.SUB_DISTRICT, L.VILLAGE_ULB
),
SubDistrictAgg AS (
    SELECT STATE, DISTRICT, SUB_DISTRICT,
           COUNT(*) AS VILLAGE_COUNT,
           SUM(POPULATION) AS TOTAL_POP,
           AVG(POPULATION) AS AVG_VILLAGE_POP,
           MIN(POPULATION) AS MIN_VILLAGE_POP,
           MAX(POPULATION) AS MAX_VILLAGE_POP
    FROM VillageStats
    GROUP BY STATE, DISTRICT, SUB_DISTRICT
),
DistrictSummary AS (
    SELECT STATE, DISTRICT,
           SUM(VILLAGE_COUNT) AS TOTAL_VILLAGES,
           SUM(TOTAL_POP) AS DISTRICT_POP,
           AVG(AVG_VILLAGE_POP) AS AVG_VILLAGE_SIZE
    FROM SubDistrictAgg
    GROUP BY STATE, DISTRICT
)
SELECT SD.STATE, SD.DISTRICT, SD.SUB_DISTRICT,
       SD.VILLAGE_COUNT, SD.TOTAL_POP,
       ROUND(SD.AVG_VILLAGE_POP, 0) AS AVG_VILLAGE_POP,
       ROUND(SD.TOTAL_POP * 100.0 / DS.DISTRICT_POP, 2) AS PCT_OF_DISTRICT,
       RANK() OVER (PARTITION BY SD.STATE, SD.DISTRICT ORDER BY SD.TOTAL_POP DESC) AS RANK_IN_DISTRICT
FROM SubDistrictAgg SD
JOIN DistrictSummary DS ON SD.STATE = DS.STATE AND SD.DISTRICT = DS.DISTRICT
ORDER BY SD.STATE, SD.DISTRICT, RANK_IN_DISTRICT;
