-- Complexity: Level 2 (Moderate)
-- Category: Literacy Analysis
SELECT L.STATE,
       SUM(LIT.LITERATE_MALE) AS LITERATE_MALE,
       SUM(LIT.LITERATE_FEMALE) AS LITERATE_FEMALE,
       ROUND(SUM(LIT.LITERATE_MALE) * 1.0 / NULLIF(SUM(LIT.LITERATE_FEMALE), 0), 2) AS MALE_FEMALE_RATIO
FROM LOCATIONS L
JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
JOIN CENSUS_LITERACY LIT ON P.CENSUS_ID = LIT.CENSUS_ID
GROUP BY L.STATE
ORDER BY MALE_FEMALE_RATIO DESC;
