-- Complexity: Level 3 (Intermediate)
-- Category: Geographic Aggregations
WITH DistrictPopulation AS (
    SELECT L.STATE, L.DISTRICT,
           SUM(P.POPULATION_TOTAL) AS POPULATION
    FROM LOCATIONS L
    JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
    GROUP BY L.STATE, L.DISTRICT
)
SELECT STATE, DISTRICT, POPULATION,
       SUM(POPULATION) OVER (PARTITION BY STATE) AS STATE_TOTAL,
       ROUND(POPULATION * 100.0 / SUM(POPULATION) OVER (PARTITION BY STATE), 2) AS PCT_OF_STATE
FROM DistrictPopulation
ORDER BY STATE, POPULATION DESC;
