-- Complexity: Level 4 (Advanced)
-- Category: Geographic Aggregations
WITH DistrictStats AS (
    SELECT L.STATE, L.DISTRICT,
           SUM(P.POPULATION_TOTAL) AS POPULATION,
           COUNT(DISTINCT L.SUB_DISTRICT) AS SUB_DISTRICTS,
           COUNT(DISTINCT L.VILLAGE_ULB) AS VILLAGES
    FROM LOCATIONS L
    JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
    GROUP BY L.STATE, L.DISTRICT
),
StateAvg AS (
    SELECT STATE,
           AVG(POPULATION) AS AVG_DISTRICT_POP,
           AVG(VILLAGES) AS AVG_VILLAGES
    FROM DistrictStats
    GROUP BY STATE
)
SELECT DS.STATE, DS.DISTRICT, DS.POPULATION, DS.VILLAGES,
       ROUND(DS.POPULATION * 1.0 / SA.AVG_DISTRICT_POP, 2) AS POP_VS_STATE_AVG,
       CASE
           WHEN DS.POPULATION > SA.AVG_DISTRICT_POP * 1.5 THEN 'Large'
           WHEN DS.POPULATION < SA.AVG_DISTRICT_POP * 0.5 THEN 'Small'
           ELSE 'Medium'
       END AS DISTRICT_SIZE
FROM DistrictStats DS
JOIN StateAvg SA ON DS.STATE = SA.STATE
ORDER BY DS.POPULATION DESC;
