-- Complexity: Level 5 (Complex)
-- Category: Caste Demographics
WITH StateMetrics AS (
    SELECT L.STATE,
           SUM(P.POPULATION_TOTAL) AS TOTAL_POP,
           SUM(C.SC_POPULATION_TOTAL) AS SC_POP,
           SUM(C.ST_POPULATION_TOTAL) AS ST_POP,
           SUM(LIT.LITERATE_TOTAL) AS LITERATE,
           SUM(LIT.LITERATE_TOTAL + LIT.ILLITERATE_TOTAL) AS ASSESSED,
           SUM(W.WORKING_TOTAL) AS WORKERS
    FROM LOCATIONS L
    JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
    JOIN CENSUS_CASTE C ON P.CENSUS_ID = C.CENSUS_ID
    JOIN CENSUS_LITERACY LIT ON P.CENSUS_ID = LIT.CENSUS_ID
    JOIN CENSUS_WORKERS_SUMMARY W ON P.CENSUS_ID = W.CENSUS_ID
    GROUP BY L.STATE
),
StateRates AS (
    SELECT STATE, TOTAL_POP,
           ROUND(SC_POP * 100.0 / NULLIF(TOTAL_POP, 0), 2) AS SC_PCT,
           ROUND(ST_POP * 100.0 / NULLIF(TOTAL_POP, 0), 2) AS ST_PCT,
           ROUND(LITERATE * 100.0 / NULLIF(ASSESSED, 0), 2) AS LITERACY_RATE,
           ROUND(WORKERS * 100.0 / NULLIF(TOTAL_POP, 0), 2) AS WORK_RATE
    FROM StateMetrics
),
Rankings AS (
    SELECT STATE, TOTAL_POP, SC_PCT, ST_PCT, LITERACY_RATE, WORK_RATE,
           RANK() OVER (ORDER BY SC_PCT DESC) AS SC_RANK,
           RANK() OVER (ORDER BY ST_PCT DESC) AS ST_RANK,
           RANK() OVER (ORDER BY LITERACY_RATE DESC) AS LITERACY_RANK,
           RANK() OVER (ORDER BY WORK_RATE DESC) AS WORK_RANK
    FROM StateRates
)
SELECT STATE, SC_PCT, ST_PCT, LITERACY_RATE, WORK_RATE,
       SC_RANK, ST_RANK, LITERACY_RANK, WORK_RANK,
       (SC_RANK + ST_RANK + LITERACY_RANK + WORK_RANK) / 4.0 AS COMPOSITE_RANK
FROM Rankings
ORDER BY COMPOSITE_RANK;
