-- Complexity: Level 3 (Intermediate)
-- Category: Employment Statistics
WITH WorkerComparison AS (
    SELECT L.STATE,
           SUM(W.MAIN_WORKERS_TOTAL) AS MAIN_WORKERS,
           SUM(W.MARGINAL_WORKERS_TOTAL) AS MARGINAL_WORKERS
    FROM LOCATIONS L
    JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
    JOIN CENSUS_WORKERS_SUMMARY W ON P.CENSUS_ID = W.CENSUS_ID
    GROUP BY L.STATE
)
SELECT STATE, MAIN_WORKERS, MARGINAL_WORKERS,
       ROUND(MARGINAL_WORKERS * 100.0 / NULLIF(MAIN_WORKERS + MARGINAL_WORKERS, 0), 2) AS MARGINAL_PCT,
       ROW_NUMBER() OVER (ORDER BY MARGINAL_WORKERS * 100.0 / NULLIF(MAIN_WORKERS + MARGINAL_WORKERS, 0) DESC) AS RANK
FROM WorkerComparison;
