-- Complexity: Level 4 (Advanced)
-- Category: Population Analytics
WITH ChildPopulation AS (
    SELECT L.STATE, L.DISTRICT,
           SUM(P.POPULATION_0_6_TOTAL) AS CHILDREN,
           SUM(P.POPULATION_0_6_MALE) AS CHILDREN_MALE,
           SUM(P.POPULATION_0_6_FEMALE) AS CHILDREN_FEMALE,
           SUM(P.POPULATION_TOTAL) AS TOTAL_POP
    FROM LOCATIONS L
    JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
    GROUP BY L.STATE, L.DISTRICT
),
ChildStats AS (
    SELECT STATE, DISTRICT, CHILDREN, TOTAL_POP,
           ROUND(CHILDREN * 100.0 / NULLIF(TOTAL_POP, 0), 2) AS CHILD_PCT,
           ROUND(CHILDREN_FEMALE * 1000.0 / NULLIF(CHILDREN_MALE, 0), 0) AS CHILD_SEX_RATIO
    FROM ChildPopulation
)
SELECT STATE, DISTRICT, CHILDREN, CHILD_PCT, CHILD_SEX_RATIO,
       AVG(CHILD_SEX_RATIO) OVER (PARTITION BY STATE) AS STATE_AVG_CHILD_SEX_RATIO,
       CHILD_SEX_RATIO - AVG(CHILD_SEX_RATIO) OVER (PARTITION BY STATE) AS DEVIATION_FROM_STATE_AVG
FROM ChildStats
WHERE CHILDREN > 1000
ORDER BY CHILD_SEX_RATIO ASC;
