-- Complexity: Level 2 (Moderate)
-- Category: Population Analytics
SELECT L.STATE, L.DISTRICT, SUM(P.HOUSEHOLDS) AS TOTAL_HOUSEHOLDS
FROM LOCATIONS L
JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
GROUP BY L.STATE, L.DISTRICT
ORDER BY TOTAL_HOUSEHOLDS DESC
LIMIT 20;
