-- Complexity: Level 2 (Moderate)
-- Category: Employment Statistics
SELECT L.STATE,
       SUM(MG.CULTIVATORS_TOTAL) AS MARGINAL_CULTIVATORS,
       SUM(MG.AGRI_LABOURERS_TOTAL) AS MARGINAL_AGRI_LABOURERS,
       SUM(MG.HOUSEHOLD_INDUSTRY_TOTAL) AS MARGINAL_HOUSEHOLD_INDUSTRY,
       SUM(MG.OTHER_WORKERS_TOTAL) AS MARGINAL_OTHER_WORKERS
FROM LOCATIONS L
JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
JOIN CENSUS_MARGINAL_WORKERS_DETAIL MG ON P.CENSUS_ID = MG.CENSUS_ID
GROUP BY L.STATE
ORDER BY MARGINAL_CULTIVATORS DESC;
