-- Complexity: Level 3 (Intermediate)
-- Category: Geographic Aggregations
WITH SubDistrictStats AS (
    SELECT L.STATE, L.DISTRICT, L.SUB_DISTRICT,
           SUM(P.POPULATION_TOTAL) AS POPULATION,
           COUNT(DISTINCT L.VILLAGE_ULB) AS VILLAGE_COUNT
    FROM LOCATIONS L
    JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
    GROUP BY L.STATE, L.DISTRICT, L.SUB_DISTRICT
)
SELECT STATE, DISTRICT, SUB_DISTRICT, POPULATION, VILLAGE_COUNT,
       ROUND(POPULATION * 1.0 / NULLIF(VILLAGE_COUNT, 0), 0) AS AVG_VILLAGE_POPULATION,
       RANK() OVER (PARTITION BY STATE ORDER BY POPULATION DESC) AS RANK_IN_STATE
FROM SubDistrictStats
WHERE VILLAGE_COUNT > 0;
