-- Complexity: Level 2 (Moderate)
-- Category: Caste Demographics
SELECT L.STATE,
       SUM(C.SC_POPULATION_TOTAL) AS SC_POPULATION,
       SUM(C.ST_POPULATION_TOTAL) AS ST_POPULATION,
       SUM(P.POPULATION_TOTAL) AS TOTAL_POPULATION
FROM LOCATIONS L
JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
JOIN CENSUS_CASTE C ON P.CENSUS_ID = C.CENSUS_ID
GROUP BY L.STATE
ORDER BY ST_POPULATION DESC;
