-- Complexity: Level 2 (Moderate)
-- Category: Population Analytics
SELECT L.STATE, P.RESIDENCE_TYPE,
       SUM(P.POPULATION_TOTAL) AS POPULATION
FROM LOCATIONS L
JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
GROUP BY L.STATE, P.RESIDENCE_TYPE
ORDER BY L.STATE, P.RESIDENCE_TYPE;
