-- Complexity: Level 2 (Moderate)
-- Category: Literacy Analysis
SELECT L.STATE, P.RESIDENCE_TYPE,
       SUM(LIT.LITERATE_TOTAL) AS LITERATE,
       SUM(LIT.ILLITERATE_TOTAL) AS ILLITERATE
FROM LOCATIONS L
JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
JOIN CENSUS_LITERACY LIT ON P.CENSUS_ID = LIT.CENSUS_ID
GROUP BY L.STATE, P.RESIDENCE_TYPE
ORDER BY L.STATE, P.RESIDENCE_TYPE;
