-- Complexity: Level 1 (Simple)
-- Category: Population Analytics
SELECT SUM(POPULATION_TOTAL) AS TOTAL_POPULATION,
       SUM(POPULATION_MALE) AS MALE_POPULATION,
       SUM(POPULATION_FEMALE) AS FEMALE_POPULATION
FROM CENSUS_POPULATION;
