-- Complexity: Level 2 (Moderate)
-- Category: Employment Statistics
SELECT L.STATE,
       SUM(W.MAIN_WORKERS_TOTAL) AS MAIN_WORKERS,
       SUM(W.MARGINAL_WORKERS_TOTAL) AS MARGINAL_WORKERS
FROM LOCATIONS L
JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
JOIN CENSUS_WORKERS_SUMMARY W ON P.CENSUS_ID = W.CENSUS_ID
GROUP BY L.STATE
ORDER BY MAIN_WORKERS DESC;
