-- Complexity: Level 5 (Complex)
-- Category: Literacy Analysis
WITH DistrictMetrics AS (
    SELECT L.STATE, L.DISTRICT,
           SUM(P.POPULATION_TOTAL) AS POPULATION,
           SUM(LIT.LITERATE_TOTAL) AS LITERATE,
           SUM(LIT.LITERATE_TOTAL + LIT.ILLITERATE_TOTAL) AS ASSESSED,
           SUM(C.SC_POPULATION_TOTAL + C.ST_POPULATION_TOTAL) AS SC_ST_POP
    FROM LOCATIONS L
    JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
    JOIN CENSUS_LITERACY LIT ON P.CENSUS_ID = LIT.CENSUS_ID
    JOIN CENSUS_CASTE C ON P.CENSUS_ID = C.CENSUS_ID
    GROUP BY L.STATE, L.DISTRICT
),
DistrictRates AS (
    SELECT STATE, DISTRICT, POPULATION,
           ROUND(LITERATE * 100.0 / NULLIF(ASSESSED, 0), 2) AS LITERACY_RATE,
           ROUND(SC_ST_POP * 100.0 / NULLIF(POPULATION, 0), 2) AS SC_ST_PCT
    FROM DistrictMetrics
    WHERE POPULATION > 10000
),
Quartiles AS (
    SELECT STATE, DISTRICT, POPULATION, LITERACY_RATE, SC_ST_PCT,
           NTILE(4) OVER (ORDER BY LITERACY_RATE) AS LITERACY_QUARTILE,
           NTILE(4) OVER (ORDER BY SC_ST_PCT DESC) AS SC_ST_QUARTILE
    FROM DistrictRates
)
SELECT STATE, DISTRICT, LITERACY_RATE, SC_ST_PCT,
       CASE LITERACY_QUARTILE
           WHEN 1 THEN 'Low Literacy'
           WHEN 2 THEN 'Below Average Literacy'
           WHEN 3 THEN 'Above Average Literacy'
           WHEN 4 THEN 'High Literacy'
       END AS LITERACY_CATEGORY,
       CASE SC_ST_QUARTILE
           WHEN 1 THEN 'High SC/ST'
           WHEN 2 THEN 'Above Average SC/ST'
           WHEN 3 THEN 'Below Average SC/ST'
           WHEN 4 THEN 'Low SC/ST'
       END AS SC_ST_CATEGORY
FROM Quartiles
ORDER BY LITERACY_RATE DESC;
