-- Complexity: Level 3 (Intermediate)
-- Category: Population Analytics
WITH StatePopulation AS (
    SELECT L.STATE,
           SUM(P.POPULATION_TOTAL) AS TOTAL_POPULATION
    FROM LOCATIONS L
    JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
    GROUP BY L.STATE
)
SELECT STATE, TOTAL_POPULATION,
       RANK() OVER (ORDER BY TOTAL_POPULATION DESC) AS POPULATION_RANK
FROM StatePopulation;
