-- Complexity: Level 2 (Moderate)
-- Category: Caste Demographics
SELECT L.STATE, L.DISTRICT,
       SUM(C.ST_POPULATION_TOTAL) AS ST_POPULATION,
       ROUND(SUM(C.ST_POPULATION_TOTAL) * 100.0 / NULLIF(SUM(P.POPULATION_TOTAL), 0), 2) AS ST_PERCENTAGE
FROM LOCATIONS L
JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
JOIN CENSUS_CASTE C ON P.CENSUS_ID = C.CENSUS_ID
GROUP BY L.STATE, L.DISTRICT
HAVING SUM(C.ST_POPULATION_TOTAL) > 0
ORDER BY ST_PERCENTAGE DESC
LIMIT 20;
