-- Complexity: Level 2 (Moderate)
-- Category: Employment Statistics
SELECT L.STATE,
       SUM(W.WORKING_TOTAL) AS WORKERS,
       SUM(W.NON_WORKERS_TOTAL) AS NON_WORKERS,
       ROUND(SUM(W.WORKING_TOTAL) * 100.0 / NULLIF(SUM(W.WORKING_TOTAL + W.NON_WORKERS_TOTAL), 0), 2) AS EMPLOYMENT_RATE
FROM LOCATIONS L
JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
JOIN CENSUS_WORKERS_SUMMARY W ON P.CENSUS_ID = W.CENSUS_ID
GROUP BY L.STATE
ORDER BY EMPLOYMENT_RATE DESC;
