-- Complexity: Level 3 (Intermediate)
-- Category: Literacy Analysis
WITH GenderLiteracy AS (
    SELECT L.STATE,
           SUM(LIT.LITERATE_MALE) AS MALE_LITERATE,
           SUM(LIT.LITERATE_FEMALE) AS FEMALE_LITERATE,
           SUM(P.POPULATION_MALE) AS MALE_POP,
           SUM(P.POPULATION_FEMALE) AS FEMALE_POP
    FROM LOCATIONS L
    JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
    JOIN CENSUS_LITERACY LIT ON P.CENSUS_ID = LIT.CENSUS_ID
    GROUP BY L.STATE
)
SELECT STATE,
       ROUND(MALE_LITERATE * 100.0 / NULLIF(MALE_POP, 0), 2) AS MALE_LITERACY_RATE,
       ROUND(FEMALE_LITERATE * 100.0 / NULLIF(FEMALE_POP, 0), 2) AS FEMALE_LITERACY_RATE,
       ROUND(MALE_LITERATE * 100.0 / NULLIF(MALE_POP, 0), 2) - ROUND(FEMALE_LITERATE * 100.0 / NULLIF(FEMALE_POP, 0), 2) AS GENDER_GAP
FROM GenderLiteracy
ORDER BY GENDER_GAP DESC;
