-- Complexity: Level 3 (Intermediate)
-- Category: Population Analytics
WITH UrbanRural AS (
    SELECT L.STATE,
           SUM(CASE WHEN P.RESIDENCE_TYPE = 'Urban' THEN P.POPULATION_TOTAL ELSE 0 END) AS URBAN_POP,
           SUM(CASE WHEN P.RESIDENCE_TYPE = 'Rural' THEN P.POPULATION_TOTAL ELSE 0 END) AS RURAL_POP
    FROM LOCATIONS L
    JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
    GROUP BY L.STATE
)
SELECT STATE, URBAN_POP, RURAL_POP,
       ROUND(URBAN_POP * 100.0 / NULLIF(URBAN_POP + RURAL_POP, 0), 2) AS URBANIZATION_RATE
FROM UrbanRural
WHERE URBAN_POP + RURAL_POP > 0
ORDER BY URBANIZATION_RATE DESC;
