-- Complexity: Level 2 (Moderate)
-- Category: Employment Statistics
SELECT L.STATE,
       SUM(M.CULTIVATORS_TOTAL) AS CULTIVATORS,
       SUM(M.AGRI_LABOURERS_TOTAL) AS AGRI_LABOURERS
FROM LOCATIONS L
JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
JOIN CENSUS_MAIN_WORKERS_DETAIL M ON P.CENSUS_ID = M.CENSUS_ID
GROUP BY L.STATE
ORDER BY CULTIVATORS DESC;
