-- Complexity: Level 3 (Intermediate)
-- Category: Caste Demographics
WITH CasteDistribution AS (
    SELECT L.STATE,
           SUM(C.SC_POPULATION_TOTAL) AS SC_POP,
           SUM(C.ST_POPULATION_TOTAL) AS ST_POP,
           SUM(P.POPULATION_TOTAL) AS TOTAL_POP
    FROM LOCATIONS L
    JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
    JOIN CENSUS_CASTE C ON P.CENSUS_ID = C.CENSUS_ID
    GROUP BY L.STATE
)
SELECT STATE,
       ROUND(SC_POP * 100.0 / NULLIF(TOTAL_POP, 0), 2) AS SC_PERCENTAGE,
       ROUND(ST_POP * 100.0 / NULLIF(TOTAL_POP, 0), 2) AS ST_PERCENTAGE,
       CASE
           WHEN ST_POP * 100.0 / NULLIF(TOTAL_POP, 0) > 50 THEN 'ST Majority'
           WHEN SC_POP * 100.0 / NULLIF(TOTAL_POP, 0) > 25 THEN 'High SC'
           ELSE 'General'
       END AS DEMOGRAPHIC_CATEGORY
FROM CasteDistribution
ORDER BY ST_PERCENTAGE DESC;
