-- Complexity: Level 5 (Complex)
-- Category: Employment Statistics
WITH OccupationBreakdown AS (
    SELECT L.STATE,
           SUM(MW.CULTIVATORS_TOTAL) + SUM(MG.CULTIVATORS_TOTAL) AS CULTIVATORS,
           SUM(MW.AGRI_LABOURERS_TOTAL) + SUM(MG.AGRI_LABOURERS_TOTAL) AS AGRI_LABOURERS,
           SUM(MW.HOUSEHOLD_INDUSTRY_TOTAL) + SUM(MG.HOUSEHOLD_INDUSTRY_TOTAL) AS HOUSEHOLD_INDUSTRY,
           SUM(MW.OTHER_WORKERS_TOTAL) + SUM(MG.OTHER_WORKERS_TOTAL) AS OTHER_WORKERS,
           SUM(WS.WORKING_TOTAL) AS TOTAL_WORKERS
    FROM LOCATIONS L
    JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
    JOIN CENSUS_MAIN_WORKERS_DETAIL MW ON P.CENSUS_ID = MW.CENSUS_ID
    JOIN CENSUS_MARGINAL_WORKERS_DETAIL MG ON P.CENSUS_ID = MG.CENSUS_ID
    JOIN CENSUS_WORKERS_SUMMARY WS ON P.CENSUS_ID = WS.CENSUS_ID
    GROUP BY L.STATE
),
OccupationPct AS (
    SELECT STATE,
           ROUND(CULTIVATORS * 100.0 / NULLIF(TOTAL_WORKERS, 0), 2) AS CULTIVATOR_PCT,
           ROUND(AGRI_LABOURERS * 100.0 / NULLIF(TOTAL_WORKERS, 0), 2) AS AGRI_LAB_PCT,
           ROUND(HOUSEHOLD_INDUSTRY * 100.0 / NULLIF(TOTAL_WORKERS, 0), 2) AS HH_IND_PCT,
           ROUND(OTHER_WORKERS * 100.0 / NULLIF(TOTAL_WORKERS, 0), 2) AS OTHER_PCT,
           CULTIVATORS + AGRI_LABOURERS AS AGRICULTURAL_WORKERS,
           HOUSEHOLD_INDUSTRY + OTHER_WORKERS AS NON_AGRICULTURAL_WORKERS,
           TOTAL_WORKERS
    FROM OccupationBreakdown
),
EconomyClassification AS (
    SELECT STATE, CULTIVATOR_PCT, AGRI_LAB_PCT, HH_IND_PCT, OTHER_PCT,
           ROUND(AGRICULTURAL_WORKERS * 100.0 / NULLIF(TOTAL_WORKERS, 0), 2) AS AGRI_SECTOR_PCT,
           ROUND(NON_AGRICULTURAL_WORKERS * 100.0 / NULLIF(TOTAL_WORKERS, 0), 2) AS NON_AGRI_SECTOR_PCT,
           CASE
               WHEN AGRICULTURAL_WORKERS > NON_AGRICULTURAL_WORKERS * 2 THEN 'Highly Agricultural'
               WHEN AGRICULTURAL_WORKERS > NON_AGRICULTURAL_WORKERS THEN 'Agricultural'
               WHEN NON_AGRICULTURAL_WORKERS > AGRICULTURAL_WORKERS * 2 THEN 'Highly Non-Agricultural'
               ELSE 'Mixed Economy'
           END AS ECONOMY_TYPE
    FROM OccupationPct
),
NationalAvg AS (
    SELECT AVG(AGRI_SECTOR_PCT) AS NAT_AGRI_PCT
    FROM EconomyClassification
)
SELECT EC.STATE, EC.CULTIVATOR_PCT, EC.AGRI_LAB_PCT, EC.HH_IND_PCT, EC.OTHER_PCT,
       EC.AGRI_SECTOR_PCT, EC.NON_AGRI_SECTOR_PCT, EC.ECONOMY_TYPE,
       ROUND(NA.NAT_AGRI_PCT, 2) AS NATIONAL_AGRI_AVG,
       ROUND(EC.AGRI_SECTOR_PCT - NA.NAT_AGRI_PCT, 2) AS DEVIATION_FROM_NATIONAL
FROM EconomyClassification EC
CROSS JOIN NationalAvg NA
ORDER BY EC.AGRI_SECTOR_PCT DESC;
