-- Complexity: Level 2 (Moderate)
-- Category: Population Analytics
SELECT L.STATE,
       SUM(P.POPULATION_0_6_TOTAL) AS CHILDREN_0_6,
       SUM(P.POPULATION_TOTAL) AS TOTAL_POPULATION,
       ROUND(SUM(P.POPULATION_0_6_TOTAL) * 100.0 / NULLIF(SUM(P.POPULATION_TOTAL), 0), 2) AS CHILD_PERCENTAGE
FROM LOCATIONS L
JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
GROUP BY L.STATE
ORDER BY CHILD_PERCENTAGE DESC;
