-- Complexity: Level 1 (Simple)
-- Category: Employment Statistics
SELECT SUM(CULTIVATORS_TOTAL) AS CULTIVATORS,
       SUM(AGRI_LABOURERS_TOTAL) AS AGRI_LABOURERS,
       SUM(HOUSEHOLD_INDUSTRY_TOTAL) AS HOUSEHOLD_INDUSTRY,
       SUM(OTHER_WORKERS_TOTAL) AS OTHER_WORKERS
FROM CENSUS_MAIN_WORKERS_DETAIL;
