-- Complexity: Level 4 (Advanced)
-- Category: Employment Statistics
WITH MainWorkers AS (
    SELECT L.STATE,
           SUM(M.CULTIVATORS_TOTAL) AS MAIN_CULTIVATORS,
           SUM(M.AGRI_LABOURERS_TOTAL) AS MAIN_AGRI_LAB,
           SUM(M.HOUSEHOLD_INDUSTRY_TOTAL) AS MAIN_HH_IND,
           SUM(M.OTHER_WORKERS_TOTAL) AS MAIN_OTHER
    FROM LOCATIONS L
    JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
    JOIN CENSUS_MAIN_WORKERS_DETAIL M ON P.CENSUS_ID = M.CENSUS_ID
    GROUP BY L.STATE
),
MarginalWorkers AS (
    SELECT L.STATE,
           SUM(MG.CULTIVATORS_TOTAL) AS MARG_CULTIVATORS,
           SUM(MG.AGRI_LABOURERS_TOTAL) AS MARG_AGRI_LAB,
           SUM(MG.HOUSEHOLD_INDUSTRY_TOTAL) AS MARG_HH_IND,
           SUM(MG.OTHER_WORKERS_TOTAL) AS MARG_OTHER
    FROM LOCATIONS L
    JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
    JOIN CENSUS_MARGINAL_WORKERS_DETAIL MG ON P.CENSUS_ID = MG.CENSUS_ID
    GROUP BY L.STATE
)
SELECT MW.STATE,
       MW.MAIN_CULTIVATORS + MG.MARG_CULTIVATORS AS TOTAL_CULTIVATORS,
       MW.MAIN_AGRI_LAB + MG.MARG_AGRI_LAB AS TOTAL_AGRI_LABOURERS,
       MW.MAIN_HH_IND + MG.MARG_HH_IND AS TOTAL_HOUSEHOLD_INDUSTRY,
       MW.MAIN_OTHER + MG.MARG_OTHER AS TOTAL_OTHER_WORKERS,
       ROUND(MG.MARG_CULTIVATORS * 100.0 / NULLIF(MW.MAIN_CULTIVATORS + MG.MARG_CULTIVATORS, 0), 2) AS MARGINAL_CULTIVATOR_PCT
FROM MainWorkers MW
JOIN MarginalWorkers MG ON MW.STATE = MG.STATE
ORDER BY TOTAL_CULTIVATORS DESC;
