-- Complexity: Level 2 (Moderate)
-- Category: Geographic Aggregations
SELECT L.STATE, L.DISTRICT,
       COUNT(DISTINCT L.SUB_DISTRICT) AS SUB_DISTRICT_COUNT,
       COUNT(DISTINCT L.VILLAGE_ULB) AS VILLAGE_COUNT
FROM LOCATIONS L
GROUP BY L.STATE, L.DISTRICT
ORDER BY VILLAGE_COUNT DESC
LIMIT 20;
