-- Complexity: Level 4 (Advanced)
-- Category: Caste Demographics
WITH SCStats AS (
    SELECT L.STATE,
           SUM(C.SC_POPULATION_MALE) AS SC_MALE,
           SUM(C.SC_POPULATION_FEMALE) AS SC_FEMALE,
           SUM(C.SC_POPULATION_TOTAL) AS SC_TOTAL
    FROM LOCATIONS L
    JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
    JOIN CENSUS_CASTE C ON P.CENSUS_ID = C.CENSUS_ID
    GROUP BY L.STATE
),
SCLiteracy AS (
    SELECT L.STATE,
           SUM(LIT.LITERATE_TOTAL) AS LITERATE
    FROM LOCATIONS L
    JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
    JOIN CENSUS_LITERACY LIT ON P.CENSUS_ID = LIT.CENSUS_ID
    JOIN CENSUS_CASTE C ON P.CENSUS_ID = C.CENSUS_ID
    WHERE C.SC_POPULATION_TOTAL > 0
    GROUP BY L.STATE
),
TotalPop AS (
    SELECT L.STATE, SUM(P.POPULATION_TOTAL) AS TOTAL
    FROM LOCATIONS L
    JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
    GROUP BY L.STATE
)
SELECT SC.STATE, SC.SC_TOTAL,
       ROUND(SC.SC_TOTAL * 100.0 / NULLIF(TP.TOTAL, 0), 2) AS SC_PCT,
       ROUND(SC.SC_FEMALE * 1000.0 / NULLIF(SC.SC_MALE, 0), 0) AS SC_SEX_RATIO
FROM SCStats SC
JOIN TotalPop TP ON SC.STATE = TP.STATE
WHERE SC.SC_TOTAL > 0
ORDER BY SC_PCT DESC;
