-- Complexity: Level 5 (Complex)
-- Category: Employment Statistics
WITH StateWorkerStats AS (
    SELECT L.STATE,
           SUM(W.WORKING_MALE) AS MALE_WORKERS,
           SUM(W.WORKING_FEMALE) AS FEMALE_WORKERS,
           SUM(P.POPULATION_MALE) AS MALE_POP,
           SUM(P.POPULATION_FEMALE) AS FEMALE_POP
    FROM LOCATIONS L
    JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
    JOIN CENSUS_WORKERS_SUMMARY W ON P.CENSUS_ID = W.CENSUS_ID
    GROUP BY L.STATE
),
WorkerRates AS (
    SELECT STATE,
           ROUND(MALE_WORKERS * 100.0 / NULLIF(MALE_POP, 0), 2) AS MALE_WORK_RATE,
           ROUND(FEMALE_WORKERS * 100.0 / NULLIF(FEMALE_POP, 0), 2) AS FEMALE_WORK_RATE
    FROM StateWorkerStats
),
RateComparison AS (
    SELECT STATE, MALE_WORK_RATE, FEMALE_WORK_RATE,
           MALE_WORK_RATE - FEMALE_WORK_RATE AS GENDER_GAP,
           AVG(MALE_WORK_RATE - FEMALE_WORK_RATE) OVER () AS AVG_GAP,
           STDDEV(MALE_WORK_RATE - FEMALE_WORK_RATE) OVER () AS STD_GAP
    FROM WorkerRates
)
SELECT STATE, MALE_WORK_RATE, FEMALE_WORK_RATE, GENDER_GAP,
       ROUND(AVG_GAP, 2) AS NATIONAL_AVG_GAP,
       CASE
           WHEN GENDER_GAP > AVG_GAP + STD_GAP THEN 'Significantly Above Average'
           WHEN GENDER_GAP > AVG_GAP THEN 'Above Average'
           WHEN GENDER_GAP < AVG_GAP - STD_GAP THEN 'Significantly Below Average'
           ELSE 'Below Average'
       END AS GAP_CATEGORY
FROM RateComparison
ORDER BY GENDER_GAP DESC;
