-- Complexity: Level 3 (Intermediate)
-- Category: Caste Demographics
WITH SCGender AS (
    SELECT L.STATE,
           SUM(C.SC_POPULATION_MALE) AS SC_MALE,
           SUM(C.SC_POPULATION_FEMALE) AS SC_FEMALE,
           SUM(C.ST_POPULATION_MALE) AS ST_MALE,
           SUM(C.ST_POPULATION_FEMALE) AS ST_FEMALE
    FROM LOCATIONS L
    JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
    JOIN CENSUS_CASTE C ON P.CENSUS_ID = C.CENSUS_ID
    GROUP BY L.STATE
)
SELECT STATE,
       ROUND(SC_FEMALE * 1000.0 / NULLIF(SC_MALE, 0), 0) AS SC_SEX_RATIO,
       ROUND(ST_FEMALE * 1000.0 / NULLIF(ST_MALE, 0), 0) AS ST_SEX_RATIO
FROM SCGender
WHERE SC_MALE > 0 OR ST_MALE > 0
ORDER BY SC_SEX_RATIO DESC;
