-- Complexity: Level 4 (Advanced)
-- Category: Literacy Analysis
WITH RuralLiteracy AS (
    SELECT L.STATE,
           SUM(LIT.LITERATE_MALE) AS RURAL_MALE_LIT,
           SUM(LIT.LITERATE_FEMALE) AS RURAL_FEMALE_LIT,
           SUM(P.POPULATION_MALE) AS RURAL_MALE_POP,
           SUM(P.POPULATION_FEMALE) AS RURAL_FEMALE_POP
    FROM LOCATIONS L
    JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
    JOIN CENSUS_LITERACY LIT ON P.CENSUS_ID = LIT.CENSUS_ID
    WHERE P.RESIDENCE_TYPE = 'Rural'
    GROUP BY L.STATE
),
UrbanLiteracy AS (
    SELECT L.STATE,
           SUM(LIT.LITERATE_MALE) AS URBAN_MALE_LIT,
           SUM(LIT.LITERATE_FEMALE) AS URBAN_FEMALE_LIT,
           SUM(P.POPULATION_MALE) AS URBAN_MALE_POP,
           SUM(P.POPULATION_FEMALE) AS URBAN_FEMALE_POP
    FROM LOCATIONS L
    JOIN CENSUS_POPULATION P ON L.LOCATION_ID = P.LOCATION_ID
    JOIN CENSUS_LITERACY LIT ON P.CENSUS_ID = LIT.CENSUS_ID
    WHERE P.RESIDENCE_TYPE = 'Urban'
    GROUP BY L.STATE
)
SELECT R.STATE,
       ROUND(R.RURAL_MALE_LIT * 100.0 / NULLIF(R.RURAL_MALE_POP, 0), 2) AS RURAL_MALE_LITERACY,
       ROUND(R.RURAL_FEMALE_LIT * 100.0 / NULLIF(R.RURAL_FEMALE_POP, 0), 2) AS RURAL_FEMALE_LITERACY,
       ROUND(U.URBAN_MALE_LIT * 100.0 / NULLIF(U.URBAN_MALE_POP, 0), 2) AS URBAN_MALE_LITERACY,
       ROUND(U.URBAN_FEMALE_LIT * 100.0 / NULLIF(U.URBAN_FEMALE_POP, 0), 2) AS URBAN_FEMALE_LITERACY
FROM RuralLiteracy R
LEFT JOIN UrbanLiteracy U ON R.STATE = U.STATE
ORDER BY R.STATE;
