-- DIM_COUNTRY
DROP TABLE IF EXISTS DIM_COUNTRY CASCADE;
CREATE TABLE DIM_COUNTRY (
	COUNTRY_ID BIGINT PRIMARY KEY,
	COUNTRY_NAME VARCHAR(20)
);

-- DIM_STATE
DROP TABLE IF EXISTS DIM_STATE CASCADE;
CREATE TABLE DIM_STATE (
	STATE_ID BIGINT PRIMARY KEY,
	COUNTRY_ID BIGINT,
	STATE_NAME VARCHAR(100),
	FOREIGN KEY (COUNTRY_ID) REFERENCES DIM_COUNTRY (COUNTRY_ID)
);

-- DIM_DISTRICT
DROP TABLE IF EXISTS DIM_DISTRICT CASCADE;
CREATE TABLE DIM_DISTRICT (
	DISTRICT_ID BIGINT PRIMARY KEY,
	STATE_ID BIGINT,
	DISTRICT_NAME VARCHAR(50),
	FOREIGN KEY (STATE_ID) REFERENCES DIM_STATE (STATE_ID)
);

-- DIM_SUB_DISTRICT
DROP TABLE IF EXISTS DIM_SUB_DISTRICT CASCADE;
CREATE TABLE DIM_SUB_DISTRICT (
	SUB_DISTRICT_ID BIGINT PRIMARY KEY,
	DISTRICT_ID BIGINT,
	SUB_DISTRICT_NAME VARCHAR(100),
	TYPE_OF_AREA VARCHAR(20),
	FOREIGN KEY (DISTRICT_ID) REFERENCES DIM_DISTRICT (DISTRICT_ID)
);

-- DIM_YEAR
DROP TABLE IF EXISTS DIM_YEAR CASCADE;
CREATE TABLE DIM_YEAR (
	YEAR_ID INTEGER PRIMARY KEY,
	YEAR_VALUE INTEGER
);

-- DIM_MONTH
DROP TABLE IF EXISTS DIM_MONTH CASCADE;
CREATE TABLE DIM_MONTH (
	MONTH_ID BIGINT PRIMARY KEY,
	YEAR_ID INTEGER,
	MONTH_VALUE VARCHAR(30),
	MONTH_NAME VARCHAR(30),
	FOREIGN KEY (YEAR_ID) REFERENCES DIM_YEAR (YEAR_ID)
);

-- FACT_OUTPATIENT_SERVICES
DROP TABLE IF EXISTS FACT_OUTPATIENT_SERVICES CASCADE;
CREATE TABLE FACT_OUTPATIENT_SERVICES (
	OUTPATIENT_ID BIGINT PRIMARY KEY,
	SUB_DISTRICT_ID BIGINT,
	MONTH_ID BIGINT,
	OUTPATIENT_ATTENDANCE_ALLOPATHIC DOUBLE PRECISION,
	FOREIGN KEY (SUB_DISTRICT_ID) REFERENCES DIM_SUB_DISTRICT (SUB_DISTRICT_ID),
	FOREIGN KEY (MONTH_ID) REFERENCES DIM_MONTH (MONTH_ID)
);

-- FACT_CHILD_IMMUNIZATION_ROUTINE
DROP TABLE IF EXISTS FACT_CHILD_IMMUNIZATION_ROUTINE CASCADE;
CREATE TABLE FACT_CHILD_IMMUNIZATION_ROUTINE (
	IMMUNIZATION_ROUTINE_ID BIGINT PRIMARY KEY,
	SUB_DISTRICT_ID BIGINT,
	MONTH_ID BIGINT,
	BCG_VACCINE DOUBLE PRECISION,
	OPV_0_BIRTH_DOSE DOUBLE PRECISION,
	OPV_1 DOUBLE PRECISION,
	OPV_2 DOUBLE PRECISION,
	OPV_3 DOUBLE PRECISION,
	PENTAVALENT_1 DOUBLE PRECISION,
	PENTAVALENT_2 DOUBLE PRECISION,
	PENTAVALENT_3 DOUBLE PRECISION,
	FOREIGN KEY (SUB_DISTRICT_ID) REFERENCES DIM_SUB_DISTRICT (SUB_DISTRICT_ID),
	FOREIGN KEY (MONTH_ID) REFERENCES DIM_MONTH (MONTH_ID)
);

-- FACT_CHILD_IMMUNIZATION_SPECIALIZED
DROP TABLE IF EXISTS FACT_CHILD_IMMUNIZATION_SPECIALIZED CASCADE;
CREATE TABLE FACT_CHILD_IMMUNIZATION_SPECIALIZED (
	IMMUNIZATION_SPECIALIZED_ID BIGINT PRIMARY KEY,
	SUB_DISTRICT_ID BIGINT,
	MONTH_ID BIGINT,
	ROTAVIRUS_1 DOUBLE PRECISION,
	ROTAVIRUS_2 DOUBLE PRECISION,
	ROTAVIRUS_3 DOUBLE PRECISION,
	IPV_1 DOUBLE PRECISION,
	IPV_2 DOUBLE PRECISION,
	VITAMIN_A_DOSE_1 DOUBLE PRECISION,
	FOREIGN KEY (SUB_DISTRICT_ID) REFERENCES DIM_SUB_DISTRICT (SUB_DISTRICT_ID),
	FOREIGN KEY (MONTH_ID) REFERENCES DIM_MONTH (MONTH_ID)
);

-- FACT_CHILD_IMMUNIZATION_BOOSTERS
DROP TABLE IF EXISTS FACT_CHILD_IMMUNIZATION_BOOSTERS CASCADE;
CREATE TABLE FACT_CHILD_IMMUNIZATION_BOOSTERS (
	IMMUNIZATION_BOOSTERS_ID BIGINT PRIMARY KEY,
	SUB_DISTRICT_ID BIGINT,
	MONTH_ID BIGINT,
	MR_MCV_1ST_DOSE_9_11_MONTHS DOUBLE PRECISION,
	MR_2ND_DOSE_16_24_MONTHS DOUBLE PRECISION,
	DPT_1ST_BOOSTER DOUBLE PRECISION,
	OPV_BOOSTER DOUBLE PRECISION,
	FOREIGN KEY (SUB_DISTRICT_ID) REFERENCES DIM_SUB_DISTRICT (SUB_DISTRICT_ID),
	FOREIGN KEY (MONTH_ID) REFERENCES DIM_MONTH (MONTH_ID)
);

-- FACT_CHILD_IMMUNIZATION_ADOLESCENT
DROP TABLE IF EXISTS FACT_CHILD_IMMUNIZATION_ADOLESCENT CASCADE;
CREATE TABLE FACT_CHILD_IMMUNIZATION_ADOLESCENT (
	IMMUNIZATION_ADOLESCENT_ID BIGINT PRIMARY KEY,
	SUB_DISTRICT_ID BIGINT,
	MONTH_ID BIGINT,
	CHILDREN_MORE_THAN_5_YEARS_DPT_5_2ND_BOOSTER INTEGER,
	CHILDREN_MORE_THAN_10_YEARS_TT10_TD10 INTEGER,
	CHILDREN_MORE_THAN_16_YEARS_TT16_TD16 INTEGER,
	FOREIGN KEY (SUB_DISTRICT_ID) REFERENCES DIM_SUB_DISTRICT (SUB_DISTRICT_ID),
	FOREIGN KEY (MONTH_ID) REFERENCES DIM_MONTH (MONTH_ID)
);

-- FACT_IMMUNIZATION_COVERAGE
DROP TABLE IF EXISTS FACT_IMMUNIZATION_COVERAGE CASCADE;
CREATE TABLE FACT_IMMUNIZATION_COVERAGE (
	IMMUNIZATION_COVERAGE_ID BIGINT PRIMARY KEY,
	SUB_DISTRICT_ID BIGINT,
	MONTH_ID BIGINT,
	FEMALE_FULLY_IMMUNIZED_9_11_MONTHS DOUBLE PRECISION,
	MALE_FULLY_IMMUNIZED_9_11_MONTHS DOUBLE PRECISION,
	FOREIGN KEY (SUB_DISTRICT_ID) REFERENCES DIM_SUB_DISTRICT (SUB_DISTRICT_ID),
	FOREIGN KEY (MONTH_ID) REFERENCES DIM_MONTH (MONTH_ID)
);

-- FACT_MATERNAL_ANC_REGISTRATION
DROP TABLE IF EXISTS FACT_MATERNAL_ANC_REGISTRATION CASCADE;
CREATE TABLE FACT_MATERNAL_ANC_REGISTRATION (
	MATERNAL_ANC_ID BIGINT PRIMARY KEY,
	SUB_DISTRICT_ID BIGINT,
	MONTH_ID BIGINT,
	PREGNANT_WOMEN_REGISTERED_FOR_ANC DOUBLE PRECISION,
	ANC_REGISTERED_WITHIN_1ST_TRIMESTER DOUBLE PRECISION,
	PW_RECEIVED_4_OR_MORE_ANC_CHECKUPS DOUBLE PRECISION,
	FOREIGN KEY (SUB_DISTRICT_ID) REFERENCES DIM_SUB_DISTRICT (SUB_DISTRICT_ID),
	FOREIGN KEY (MONTH_ID) REFERENCES DIM_MONTH (MONTH_ID)
);

-- FACT_MATERNAL_VACCINES_MEDICATIONS
DROP TABLE IF EXISTS FACT_MATERNAL_VACCINES_MEDICATIONS CASCADE;
CREATE TABLE FACT_MATERNAL_VACCINES_MEDICATIONS (
	MATERNAL_VACCINES_ID BIGINT PRIMARY KEY,
	SUB_DISTRICT_ID BIGINT,
	MONTH_ID BIGINT,
	PW_GIVEN_TT1_TD1 DOUBLE PRECISION,
	PW_GIVEN_TT2_TD2 DOUBLE PRECISION,
	PW_GIVEN_TT_BOOSTER_TD_BOOSTER DOUBLE PRECISION,
	PW_GIVEN_ALBENDAZOLE_AFTER_1ST_TRIMESTER DOUBLE PRECISION,
	PW_PROVIDED_FULL_COURSE_180_IFA_TABLETS DOUBLE PRECISION,
	PW_PROVIDED_FULL_COURSE_360_CALCIUM_TABLETS DOUBLE PRECISION,
	MOTHERS_PROVIDED_FULL_COURSE_180_IFA_AFTER_DELIVERY DOUBLE PRECISION,
	FOREIGN KEY (SUB_DISTRICT_ID) REFERENCES DIM_SUB_DISTRICT (SUB_DISTRICT_ID),
	FOREIGN KEY (MONTH_ID) REFERENCES DIM_MONTH (MONTH_ID)
);

-- FACT_MATERNAL_HEALTH_TESTING
DROP TABLE IF EXISTS FACT_MATERNAL_HEALTH_TESTING CASCADE;
CREATE TABLE FACT_MATERNAL_HEALTH_TESTING (
	MATERNAL_TESTING_ID BIGINT PRIMARY KEY,
	SUB_DISTRICT_ID BIGINT,
	MONTH_ID BIGINT,
	HAEMOGLOBIN_TESTS_CONDUCTED DOUBLE PRECISION,
	PW_TESTED_HB_4_OR_MORE_TIMES DOUBLE PRECISION,
	PW_HB_LESS_THAN_11 DOUBLE PRECISION,
	FOREIGN KEY (SUB_DISTRICT_ID) REFERENCES DIM_SUB_DISTRICT (SUB_DISTRICT_ID),
	FOREIGN KEY (MONTH_ID) REFERENCES DIM_MONTH (MONTH_ID)
);

-- FACT_IMMUNIZATION_SESSIONS
DROP TABLE IF EXISTS FACT_IMMUNIZATION_SESSIONS CASCADE;
CREATE TABLE FACT_IMMUNIZATION_SESSIONS (
	IMMUNIZATION_SESSION_ID BIGINT PRIMARY KEY,
	SUB_DISTRICT_ID BIGINT,
	MONTH_ID BIGINT,
	IMMUNISATION_SESSIONS_PLANNED DOUBLE PRECISION,
	IMMUNISATION_SESSIONS_HELD DOUBLE PRECISION,
	IMMUNISATION_SESSIONS_WITH_ASHA_PRESENT DOUBLE PRECISION,
	FOREIGN KEY (SUB_DISTRICT_ID) REFERENCES DIM_SUB_DISTRICT (SUB_DISTRICT_ID),
	FOREIGN KEY (MONTH_ID) REFERENCES DIM_MONTH (MONTH_ID)
);

-- FACT_FAMILY_PLANNING
DROP TABLE IF EXISTS FACT_FAMILY_PLANNING CASCADE;
CREATE TABLE FACT_FAMILY_PLANNING (
	FAMILY_PLANNING_ID BIGINT PRIMARY KEY,
	SUB_DISTRICT_ID BIGINT,
	MONTH_ID BIGINT,
	COMBINED_ORAL_PILL_CYCLES_DISTRIBUTED DOUBLE PRECISION,
	CONDOM_PIECES_DISTRIBUTED DOUBLE PRECISION,
	FOREIGN KEY (SUB_DISTRICT_ID) REFERENCES DIM_SUB_DISTRICT (SUB_DISTRICT_ID),
	FOREIGN KEY (MONTH_ID) REFERENCES DIM_MONTH (MONTH_ID)
);

-- FACT_PREGNANCY_TESTING
DROP TABLE IF EXISTS FACT_PREGNANCY_TESTING CASCADE;
CREATE TABLE FACT_PREGNANCY_TESTING (
	PREGNANCY_TESTING_ID BIGINT PRIMARY KEY,
	SUB_DISTRICT_ID BIGINT,
	MONTH_ID BIGINT,
	PREGNANCY_TEST_KITS_USED DOUBLE PRECISION,
	FOREIGN KEY (SUB_DISTRICT_ID) REFERENCES DIM_SUB_DISTRICT (SUB_DISTRICT_ID),
	FOREIGN KEY (MONTH_ID) REFERENCES DIM_MONTH (MONTH_ID)
);
